### ISSUE TITLE
[Quest][Westfall] Feast or Famine

### ISSUE THREAD

**Issue by ManaInfectedRP** [holydeew/WoWHellgarve-Legion#100]
https://www.wowhead.com/quest=26230/feast-or-famine

Quest doesn't drop any Fresh Dirt https://www.wowhead.com/item=57789/fresh-dirt

**Comment by ManaInfectedRP** [comment]
nvm just a very low drop rate even tho it is supposed to drop from every dirt pile

**Comment by skeezerbean** [comment]
Our chance is ~28%, and wowhead shows ~34%
I'll bump ours up
