### ISSUE TITLE
[spell=137639] [Monk] : Storm, earth and fire

### ISSUE THREAD

**Issue by atr00025** [holydeew/WoWHellgarve-Legion#101]
Earth and fire spirits aren't copying my attacks and they stand still for like 5 seconds after being used. 
Also they don't swap targets to mark enemies with [spell=228287] [Mark of the crane] to further increase the damage of [spell=101546] [Spinning crane kick] which is the main AOE Dps spell for wind walker monks.

**Comment by skeezerbean** [comment]
Mark of the crane is applied when you use Spinning Crane Kick. It increases based on the number of unique targets hit by other abilities in the past 15 seconds as the tooltip suggests.

To get the 2nd summoned to attack, you use to use the Storm Earth and Fire again on any target, which is what prompts them to all attack. See this for more info - https://www.wowhead.com/spell=137639/storm-earth-and-fire#comments:id=1834367
