### ISSUE TITLE
[npc=107435] [Court Of Stars] [Suspicious Noble]

### ISSUE THREAD

**Issue by atr00025** [holydeew/WoWHellgarve-Legion#103]
After killing Talixae Flamewreath, players have to be in disguise to find one spy out of 16 suspicious nobles. But even if I tried asking all of them, there is no spy in there. So we can't kill the spy (a demon in disguise which drops the key to open the door to the last boss) and hence last boss [npc=101831] [advisor-melandrus] can't be killed. So the dungeon can't be completed.

How it should work?
One out of 16 suspicious nobles in the hall should be a spy (a demon in disguise).

**Comment by skeezerbean** [comment]
Fixed
