### ISSUE TITLE
[Spell] [Demon hunter] - Felblade

### ISSUE THREAD

**Issue by Oozakii** [holydeew/WoWHellgarve-Legion#105]
https://www.wowhead.com/spell=213241/felblade
the issue happen when you change activity or when you relog into the game, the spell become gray and impossible to use... to reproduce the bug take a demon hunter an select that talent (felblade) once did try to relog and the bug will happen. the correct behavior is that this spell must always be possible to use. the effect and the spell by herself works as intended

**Comment by skeezerbean** [comment]
Sending in a fix for this
