### ISSUE TITLE
[Quest] [Dreadscar Rift] Heart of the Dreadscar | quest=40731 | cant be completed

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#109]
While the Quest 
https://www.wowhead.com/quest=40731/the-heart-of-the-dreadscar

The Quest cant be completed.

The HP of  https://www.wowhead.com/npc=101468/jagganoth wont reach 0
Also Jagganoth does use his skills to often and deals a bit to much dmg in the short time. Maybe his autoattacks are also bugged.

**Comment by UrzaPlaneswalker** [comment]
Work around so far just ask a GM to kill the npc

**Comment by skeezerbean** [comment]
No work-around needed. If his conversation is still taking place then it will wait before he finishes and then dies. Until then, he's invulnerable.  After this, the heart appears above him (not blizz-like but works) to update. If this isn't the case then please let me know. The Warlock campaign should be good at least until getting all artifacts and the beginning followers

Timing of skills can be adjusted if needed.

**Comment by skeezerbean** [comment]
Sent in a fix for this. It only was an issue if you die in the first attempt, after that it resets and doesn't advance. Dropping the quest and teleporting back to dalaran and getting it again would have resolved, but at least once the fix is applied it should work a bit smoother.
