### ISSUE TITLE
[Vendor] Old Whitenose

### ISSUE THREAD

**Issue by Oozakii** [holydeew/WoWHellgarve-Legion#111]
he must sell dragon turtles mount but actually you cannot interact with him
![image](https://user-images.githubusercontent.com/114102014/192160625-a9cc133f-d586-4bb8-9833-0c675d9a5328.png)

**Comment by skeezerbean** [comment]
Works as intended - https://www.wowhead.com/npc=65068/old-whitenose#comments:id=1719706
