### ISSUE TITLE
[Quest] [Val'sharah] Wisp in the willows | quest=39354 | Event does not work

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#112]
By interact withe Whisp https://www.wowhead.com/npc=110572/wisp

i obtain the buff but i do not get transformed / do not enter the vehicle.

Also Event does not start as intended.

In quest area it looks like "Trained Compy" is a placeholder for the hidden quest kill bunny there and event essets are not at place.

https://www.wowhead.com/quest=39354/wisp-in-the-willows

It looks like it can be completed after all "Trained Compy" are killed. But they are an invalid Target.

**Comment by skeezerbean** [comment]
Fix was sent in for this
