### ISSUE TITLE
[Quest] [Val'sharah] solid as a rock | quest=38235 | Is Autocompleted

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#113]
This quest is out of line.
The quest is on autocomplete that is not intend.

https://www.wowhead.com/npc=93644/delthanar-sagewood-rescued
and
https://www.wowhead.com/npc=93602/marnor-lorleaf-rescued
can be rescued but does not count to quest completion

https://www.wowhead.com/npc=93640/erwind-mistfen-rescued
cant be interacted with

Looks like the other things for the bonus objective there work as intended.

https://www.wowhead.com/npc=100872/stoneblood-ravager#abilities
Applies https://www.wowhead.com/spell=182815/stoneblood-poison as intended but it cant be removed by jumping.

https://www.wowhead.com/quest=38235/solid-as-a-rock

**Comment by skeezerbean** [comment]
Quest works, I don't see this ability listed for this NPC anywhere
