### ISSUE TITLE
[Quest] [Val'sharah] death to the witchmother | quest=38225 | Is Autocompleted

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#114]
The quest https://www.wowhead.com/quest=38225/death-to-the-witchmother
is autocompleted this is not intended.

https://www.wowhead.com/npc=91130/magula
Is spawned and can be killed. But kill does not count to questcompletion.

Mob works as intend so far

**Comment by skeezerbean** [comment]
Fixed
