### ISSUE TITLE
[Quest] [Val'sharah] Bonus Objective: The Moonclaw Vale | quest=38469 | Serval NPC and Objects cant be interact with

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#115]
https://www.wowhead.com/quest=38469/bonus-objective-the-moonclaw-vale 
quest seems to be not the same but there is none with same name listed

Serval NPC and Objects cant be interact with

https://www.wowhead.com/npc=95617/moonclaw-druid is not a Interactive

https://www.wowhead.com/object=242275/nightmare-totem is not Interactive Objects 

Quest can be completed by killing mobs

**Comment by skeezerbean** [comment]
Fixes being sent in
