### ISSUE TITLE
[Quest] [Val'sharah] The Nightmare Lord | quest=40573 | Quest is out of line

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#116]
https://www.wowhead.com/quest=40573/the-nightmare-lord Is out of line

Also there are to many mobs spawned in the whole area sometimes 3 or 4 instead of 1

Quest can be completed

**Comment by skeezerbean** [comment]
Some are extras and being removed, others phase in during the world quest when it's active and will have more than usual. Fixes being sent in
