### ISSUE TITLE
[Questline] [Val'sharah]  Archdruid of the Claw | quest=38142 | does not lead to the next quests

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#117]
https://www.wowhead.com/quest=38142/archdruid-of-the-claw can be completed two times but does not lead somewhere

Quest start and End is for both
https://www.wowhead.com/npc=94179/aranelle

Usual followquest
https://www.wowhead.com/quest=38922/littlefur Is not out of line

**Comment by UrzaPlaneswalker** [comment]
Completing https://www.wowhead.com/quest=38922/littlefur does not lead somewhere does not lead to the next quest
Completing it starts https://www.wowhead.com/quest=38246/totemic-call without showing questwindow

https://www.wowhead.com/quest=38246/totemic-call  Works as intend

**Comment by UrzaPlaneswalker** [comment]
Frenzied Furbolgs https://www.wowhead.com/quest=38455/frenzied-furbolgs Is out of line
but works as intend

https://www.wowhead.com/quest=38143/awakening-the-archdruid Is out of line 

https://www.wowhead.com/npc=91223/koda-steelclaw is not where she should be in this part of the quest

https://www.wowhead.com/quest=38144/the-demons-below Is out of line after completing [Frenzied Furbolgs](https://www.wowhead.com/quest=38455/frenzied-furbolgs)

https://www.wowhead.com/npc=99032/kill-credit-open-bramble-wall Is invisible but can be interact

https://www.wowhead.com/quest=38145/out-of-the-dream Is out of line after completing https://www.wowhead.com/quest=38143/awakening-the-archdruid


https://www.wowhead.com/quest=38147/entangled-dreams seems to be in order
Quest can be completed as intend.

**Comment by skeezerbean** [comment]
Most of this should be fixed, if not all. If not, please resubmit with updated info. Most of the koda/littlefur quests in that area are now in order, and also phase NPCs to be friendly once completed. Bramble wall visible, Koda spawns/phased where needed.
