### ISSUE TITLE
[NPC] Stinger Wasp | npc=9111 | Does to much dmg

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#118]
https://www.wowhead.com/npc=91118/stinger-wasp

Is a Pet of https://www.wowhead.com/npc=93578/smolderhide-hunter

**Comment by UrzaPlaneswalker** [comment]
https://imgur.com/a/FVkDohD

**Comment by skeezerbean** [comment]
A fix for this, and other NPCs like it with the damage issues, should now be live or will be during the next server restart
