### ISSUE TITLE
[Quest] [Dreadscar Rift] Further advancement | quest=46784 | is on Autocomplete

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#119]
https://www.wowhead.com/quest=46784/further-advancement is Autocompleted

NPC https://www.wowhead.com/npc=108018/archivist-melinda is not spawned

Quest can be completed as intend.

**Comment by skeezerbean** [comment]
This was fixed at some point, this quest only appears once at least 1 level has been researched and you've reached a certain level
