### ISSUE TITLE
[Quest] Master and Servant | quest=11730 | reprogramed robot pet attacks player

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#120]
On quest 
https://www.wowhead.com/wotlk/de/quest=11730/master-and-servant
After using item on dead mob the mob will attack you. This is not intend

as much i know this mobs are the targetable for this item
https://www.wowhead.com/wotlk/npc=25753/sentry-bot-57-k
https://www.wowhead.com/wotlk/npc=25758/defendo-tank-66d
https://www.wowhead.com/wotlk/npc=25752/scavenge-bot-004-a8
i dont know about more mobs

**Comment by skeezerbean** [comment]
Sending in a fix
