### ISSUE TITLE
[Quest] [Borean Tundra] The Art of Persuasion | quest=11648 | Quest gives no responce of progression

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#123]
In Quest
https://www.wowhead.com/wotlk/quest=11648/the-art-of-persuasion

Npc
https://www.wowhead.com/wotlk/npc=25478/imprisoned-beryl-sorcerer
whispers no dialogue when using https://www.wowhead.com/wotlk/item=34811/neural-needler in it this is not intend.

this way players can see no progression of the quest and it appears bugged

Quest can be completed as intend

**Comment by skeezerbean** [comment]
Sent in a fix for this, as well as using the prototype needler you can buy upstairs
