### ISSUE TITLE
Draenor Garrison doesn't work

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#124]
After completing the introduction questline for WoD, the Garrison isn't built and the Garrison Hearthstone doesn't work (it gives an animaton, but no teleport).
As far as I see there isn't any possibility to enter Draenor except for Stormshield and Ashran.

**Comment by Oozakii** [comment]
to resolve the problem of "not entering draenor" you can actually use dungeon finder to join skyreach or raid finder to join highmaul and exit the instances to be in draenor, then you have to walk by yourself to unlock flypoints around.

**Comment by Knuddelmon** [comment]
Ok, found the problem. If you're mounted when speaking to Baros Alexston, the cinematic will not trigger and the garrison will not be built. So DO NOT BE MOUNTED when you speak to Baros Alexston.
When the garrison is built succesfully, the Garrison Hearthsone works as intended.

**Comment by skeezerbean** [comment]
Ddraig sent in a fix for this, at least for Alliance side. Closing for now, he should be sending some Horde updates for it as well before long if it's also the same issue.
