### ISSUE TITLE
[Quest] [Borean Tundra] Help Those That Cannot Help Themselves | quest=11876 | is exploidable

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#125]
In the quest https://www.wowhead.com/wotlk/quest=11876/help-those-that-cannot-help-themselves

Some of the 
https://www.wowhead.com/wotlk/npc=25850/trapped-mammoth-calf
can be interacted with https://www.wowhead.com/wotlk/item=35228/d-e-h-t-a-trap-smasher multiple times. This is not intend.

**Comment by skeezerbean** [comment]
Sent in a fix for this
