### ISSUE TITLE
[Bug] [Borean Tundra] debuff Animal Blood | spell=46221 | does not turn npc faction D.E.H.T.A. hostile

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#126]
The debuff https://www.wowhead.com/wotlk/spell=46221/animal-blood 
is applyed on kill by most Beasts in https://www.wowhead.com/npcs/beasts?filter=6;3537;0#0+3+9 Borean Tundra 
most apply of the debuff works as intended.

I made a list for checking. This are the Beasts i know for sure that apply the debuff

Works not as iintended:

Mammoth group:
https://www.wowhead.com/npc=24613/mammoth-calf **does apply**  https://www.wowhead.com/wotlk/spell=46221/animal-blood
**works as intended.**

https://www.wowhead.com/npc=24614/wooly-mammoth **does apply**  https://www.wowhead.com/wotlk/spell=46221/animal-blood **works as intended.**

https://www.wowhead.com/npc=25743/wooly-mammoth-bull **does apply**  https://www.wowhead.com/wotlk/spell=46221/animal-blood **works as intended.**

Works not as intended:

Caribou group:
https://www.wowhead.com/npc=25680/marsh-caribou **does not apply** https://www.wowhead.com/wotlk/spell=46221/animal-blood on kill this **is not intended.**

https://www.wowhead.com/npc=25829/marsh-fawn **does not apply** https://www.wowhead.com/wotlk/spell=46221/animal-blood on kill this **is not intend.**

Rhino group:
https://www.wowhead.com/npc=25488/wooly-rhino-calf **does not apply** https://www.wowhead.com/wotlk/spell=46221/animal-blood on kill this **is not intended.**

https://www.wowhead.com/npc=25487/wooly-rhino-matriarch **does not apply** https://www.wowhead.com/wotlk/spell=46221/animal-blood on kill this **is not intended.**

https://www.wowhead.com/npc=25489/wooly-rhino-bull **does not apply** https://www.wowhead.com/wotlk/spell=46221/animal-blood on kill this **is not intended.**

**Comment by skeezerbean** [comment]
Sent in a fix for those NPCs to properly add this aura, removed a weird feign death to some of them. The DEHTA druids will now also respond aggressively to anyone who comes near them with this aura
