### ISSUE TITLE
[Bug] [Borean Tundra] "Loot Crazed" mobs group do not drop | item=35188 | [Nesingwary Lackey Ear] as intended

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#127]
While on quest The Mobs:  https://www.wowhead.com/quest=11866/ears-of-our-enemies **do drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear as intended. item=35188 **this is intended.**

After completing https://www.wowhead.com/quest=11866/ears-of-our-enemies quest=11866 The Mobs: **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

So quest https://www.wowhead.com/quest=11867/cant-get-ear-nough quest=11867 **can not be completed.**

The Mobs: 

https://www.wowhead.com/npc=25806/loot-crazed-poacher **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25836/loot-crazed-diver **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25979/loot-crazed-hunter **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25880/minion-of-kaw **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25800/clam-master-k **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25839/northsea-mercenary **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

https://www.wowhead.com/npc=25843/northsea-thug **do not drop** https://www.wowhead.com/item=35188/nesingwary-lackey-ear **this is not intended.**

**Comment by skeezerbean** [comment]
I had zero issues having these drop from each of these NPCs
