### ISSUE TITLE
 [Quest] [Hall of the Guardian] The Tirisgarde Reborn doesn't work.

### ISSUE THREAD

**Issue by GraysonCarlyle** [holydeew/WoWHellgarve-Legion#131]
The Quest [The Tirisgarde Reborn](https://www.wowhead.com/quest=41124/the-tirisgarde-reborn) from [Meryl Felstorm](https://www.wowhead.com/npc=102700/meryl-felstorm) could not be completed because the  Objective: 
Receive your new title
was not given after listening to the NPC.

A game Admin helped me to solve this.
This Ticket is created because the Admin asked me to open it.

**Comment by skeezerbean** [comment]
This will be fixed shortly once I send Holy the file once the rest has been tested for Mage Class Hall
