### ISSUE TITLE
 [Quest] The Edge of Winter - Lord Everblaze does not drop "Everburning Ember"

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#132]
When you have one of these Quests
https://www.wowhead.com/quest=13670/the-edge-of-winter
13616
13675
13743
13748
13754
13759
13764
13770
13775
13780
13785

Lord Everblaze (https://www.wowhead.com/npc=33289/lord-everblaze) should drop "Eveburning Ember" (https://www.wowhead.com/item=45005/everburning-ember). This item is needed to unfreeze Maiden of Winter's Breath Lake (https://www.wowhead.com/npc=33303/maiden-of-winters-breath-lake) who should then give the player Winter's Edge (https://www.wowhead.com/item=45003/winters-edge).

**Comment by skeezerbean** [comment]
Sent in a fix for this
