### ISSUE TITLE
[Quest] A Cub's Cravings - Shardtooth Meat doesn't drop

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#135]
When on the quest "A Cub's Cravings" (https://www.wowhead.com/quest=29035/a-cubs-cravings)
the Shardtooth Meat (https://www.wowhead.com/item=12622/shardtooth-meat) doen't drop.
It should drop from
Shardtooth Bear (https://www.wowhead.com/npc=7444/shardtooth-bear)
Rabid Shardtooth (https://www.wowhead.com/npc=7446/rabid-shardtooth)
Shardtoothe Mauler (https://www.wowhead.com/npc=7443/shardtooth-mauler)

**Comment by skeezerbean** [comment]
Sent in a fix for this
