### ISSUE TITLE
[Bug] [Dun Morogh] Rallying the Defenders | quest=26085 | Questitem gets player stuck | Quest can be completed.

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#136]
In the Quest
https://www.wowhead.com/quest=26085/rallying-the-defenders quest=26085

The use-item for the quest
ttps://www.wowhead.com/item=56809/ironforge-banner item=56809

the gameobject spawns on directly on player and gets player stuck inside for a moment.

The bug is minor.

Quest can be completed.

**Comment by skeezerbean** [comment]
Sent in a fix to resolve this. The issue was a bad spell and the work-around was to do some really weird stuff so the player didn't remain stuck in an object for 30 seconds, but it was still awful. It will now be fixed fully.
