### ISSUE TITLE
[Bug] [Kezan] Keys to the Hot Rod | item=46856 | got some bugs but works okay

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#137]
The Hodrod thats summoned withe 
https://www.wowhead.com/item=46856/keys-to-the-hot-rod  item=46856

https://www.wowhead.com/spell=66300/punch-it spell=66300
gets the vehicle stuck for a moment but then gives player movement speed as intended maybe a animation is not loading or missing.

https://www.wowhead.com/spell=66299/radio spell=66299
Once turned on the music cant be turned off again, nothing helps but relog.

**Comment by skeezerbean** [comment]
Update being sent in to address things
