### ISSUE TITLE
[Bug] [Kezan] Bilgewater Buccaneer npc=ids inside |  has a very slow respawn after use | need for next quest

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#138]
Not sure what is the right one
https://www.wowhead.com/npc=37179/bilgewater-buccaneer npc=37179
https://www.wowhead.com/npc=48526/bilgewater-buccaneer npc=48526
de-spawns after using it and let the player wait like 3 minutes.
New players might get confused when they do the quest 
https://www.wowhead.com/quest=24502/necessary-roughness  
before and the vehicle is just gone for 3 minutes.

**Comment by skeezerbean** [comment]
This should be MUCH easier to do now. The NPCs you "play" against are only summoned while the player is in the vehicle, and in your personal visibility. They constantly will spawn as long as you're in the vehicle and haven't completed yet
