### ISSUE TITLE
[Quest] [Kezan] Fourth and Goal | quest=24503 | is hard to complete 

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#139]
The quest 
https://www.wowhead.com/quest=24503/fourth-and-goal quest=24503
needs to many attempts. The player needs to hit an exact spot on the sky. 

That is problematic the area is to small to find it in a easy way.

Quest can be completed.

**Comment by skeezerbean** [comment]
I must have fixed this at some point. I repeatedly got the quest and kicked to multiple spots between stacks, and all completed it
