### ISSUE TITLE
[Quest] [Kezan] Life of the Party | quest=14113 | some npcs are not in the right status | but quest can be completed

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#140]
On quest 
https://www.wowhead.com/quest=14113/life-of-the-party

Some of the guests got not other status so the skills are not needed to get credit this is not intended.

The other spells are useless without npcs in the right status.

Quest can be completed

**Comment by skeezerbean** [comment]
There are 58 NPCs part of this quest, all are in the same phase, and all respond to the actions, and all are visible during this quest
