### ISSUE TITLE
[Bug] or not ? [Northshire Valley] i could do a human only quest withe my gnome mage but or feature? 

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#143]
https://www.wowhead.com/human says no race only quests
but wiki tells otherwise
https://wowpedia.fandom.com/wiki/Northshire_Valley#Quests

[Northshire Valley] has only  quest that can be completed for non-humans.. clarification is needed here. 
https://www.wowhead.com/quest=26391/extinguishing-hope

https://wowpedia.fandom.com/wiki/Human_starting_experience tell it should not be possible

no idea what true

**Comment by skeezerbean** [comment]
wowhead shows some quests as specific classes, and not very many as specific races. A lot was changed so achievements could still be completed in other starter zones that were accessible after starting from another. I don't think it's a bug so I'll close for now. A lot has changed over time for this
