### ISSUE TITLE
[Quest Jewelcrafting] Swift Vengeance - Harold Winston doesn't drop Bag of Real Jewels.

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#144]
For the Quest "Swift Vengeance" (https://www.wowhead.com/quest=40531/swift-vengeance) you have to retrieve "Bag of Real Jewels" (https://www.wowhead.com/item=132259/bag-of-real-jewels) from (https://www.wowhead.com/npc=100671/harold-winston).
Gossip works so far, he turns hostile and can be killed, he just doesn't drop the item.

**Comment by skeezerbean** [comment]
Sending in a fix for this, as well as limiting the gossip to only show while quest is active
