### ISSUE TITLE
[Quest] [Azuremyst Isle] The Kurken is Lurkin' | quest=9570 | Questmob is missing

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#145]
On the quest
https://www.wowhead.com/quest=9570/the-kurken-is-lurkin quest=9570
the mob
https://www.wowhead.com/npc=17447/the-kurken npc=17447
the player needs to kill is not spawned.

The quest can not be completed otherwise.

**Comment by skeezerbean** [comment]
This should now be fixed, and NPC phased properly
