### ISSUE TITLE
[Quest] [Bloodmyst Isle] I Shoot Magic Into the Darkness | quest=9700 | Had some kind of count bug

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#146]
On quest
https://www.wowhead.com/quest=9700/i-shoot-magic-into-the-darkness quest=9700
I had problems to kill number 5 of the mobs
https://imgur.com/a/8FtC0Z5

https://www.wowhead.com/npc=17550/void-anomaly npc=17550

The part with the portal was as intended.

The Quest was on autocomplete after a few relogs.

So the Quest could be completed. But here is still maybe an error

**Comment by skeezerbean** [comment]
There's a fix for this in that it won't update the investigate location part until you've killed the 5 NPCs, otherwise it bugs and the kills no longer count. Until some other issues are fixed in the core this is about the best I could do that so it would update objectives properly.
