### ISSUE TITLE
[Quest] [Bloodmyst Isle] Razormaw quest=9689 | Questmob has no levelscaling

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#147]
In the quest
https://www.wowhead.com/quest=9689/razormaw quest=9689

when summon 
https://www.wowhead.com/npc=17592/razormaw npc=17592
the mob got no level scaling and spawns withe lvl 20.

The Quest can be completed.

**Comment by skeezerbean** [comment]
Sending in a fix for scaling
