### ISSUE TITLE
[Quest] [Azuremyst Isle] Show Gnomercy | quest=9537 | Mob does not drop item

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#148]
In the quest
https://www.wowhead.com/quest=9537/show-gnomercy quest=9537

the questmob
https://www.wowhead.com/npc=17243/engineer-spark-overgrind npc=17243
does not drop
https://www.wowhead.com/item=23899/traitors-communication item=23899
this is not intended. Chance should be 100%

Quest cant be completed.

**Comment by skeezerbean** [comment]
Sent in a fix for this
