### ISSUE TITLE
[Quest] [Bloodmyst Isle] Urgent Delivery quest=9671 | gots a maybe complex problem

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#149]
When getting quest 
https://www.wowhead.com/quest=9671/urgent-delivery quest=9671
from
https://www.wowhead.com/npc=17703/messenger-hermesius npc=17703
and then abandon the quest it cant be reaccepted and the quest is not showing up again.

I tested this with a drenai.

Then i tested the triggerquest for that npc to show that quest up 

https://www.wowhead.com/quest=9506/a-small-start quest=9506
but i did this with a gnome

and
https://www.wowhead.com/npc=17703/messenger-hermesius npc=17703
had no quest

https://www.wowhead.com/quest=9671/urgent-delivery quest=9671
for the gnome

**Comment by skeezerbean** [comment]
I'm not sure what you mean by trigger quest. This quest is auto completed, and afterwards you get mail in your mailbox. The item in the mail starts the quest https://www.wowhead.com/quest=9672/the-bloodcurse-legacy

If you abandon the quest 9672 then you can go talk to Admiral Odysyus (who the letter is supposed to be from) and request another letter to restart the quest. This is working as intended, see the screenshot

![image](https://user-images.githubusercontent.com/19826665/217386898-8f21adfd-0fcd-4fc4-aca5-638b3e9ed8be.png)
