### ISSUE TITLE
[Quest] [Bloodmyst Isle] The Bloodcursed Naga quest=9674 | Does not apply buff to player

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#150]
On quest
https://www.wowhead.com/quest=9674/the-bloodcursed-naga quest=9674

the npc
https://www.wowhead.com/npc=17712/captain-edward-hanes npc=17712
did not apply the player
https://www.wowhead.com/spell=31319/the-captains-kiss spell=31319
on interaction this is not intended.

The quest can be completed

**Comment by skeezerbean** [comment]
This fix was sent to Holy and applied, so the next time the server restarts it should be active
