### ISSUE TITLE
Rise, champions

### ISSUE THREAD

**Issue by JeanXzZ** [holydeew/WoWHellgarve-Legion#152]
One quest:
https://www.wowhead.com/quest=42663/rise-champions 

The npc's:
https://www.wowhead.com/champion=717/archmage-modera 

https://www.wowhead.com/champion=716/archmage-kalec

The quest can't be completed, Unable to recruit followers due to no option appearing, even after resuming the quest.

**Comment by skeezerbean** [comment]
This should be fixed in the Mage Class Hall update which I'll be sending to Holy soon. This quest was a bit out of order, and Modera/Kalec showed their recruitment as an option before this quest was taken. That will also be fixed as well as the phasing.
