### ISSUE TITLE
[Quest] [Plaguelands] Death comes from on high | Quest= 12641 | Eye of archerus locked move

### ISSUE THREAD

**Issue by AdaliussS** [holydeew/WoWHellgarve-Legion#160]
The eye of archerus is blocked from moving up and down, therefore the objective of analyzing the new avalon forge cannot be completed.
(im using traductor)
https://www.wowhead.com/wotlk/quest=12641/death-comes-from-on-high
The quest consists of analyzing 4 points on the map, the eye of archerus, it moves very slowly which makes it uncomfortable, and it only moves on a single axis, it cannot go up or down, which makes it impossible to meet the objective. I would say that a possible solution is to increase the flight speed a bit using the archerus eye, and 3 options:
-Lower the axis a little to the point that you can analyze the 4 locations.
-Unlock the axis and give full mobility to the eye of archerus to be able to meet the objectives.
-Auto complete the mission or the objective that is impossible, which would be the forge of a new avalon.
It's basically an important mission that you can't skip.

So new death knights will not be able to get past that point.
Post Data: I understand that this reporting system helps to share and understand server problems and bugs, but not everyone would be willing to take their time to report and fix it. I will try to help as much as possible to report all bugs. Good luck, I hope you can fix the problem.

**Comment by skeezerbean** [comment]
This does work, but you have to hit space bar to jump. For whatever reason the vehicle refuses to acknowledge that it can raise or lower.
Sometimes the pet actions also don't show on the bar, and the aura can be canceled and gotten again and should resolve.
