### ISSUE TITLE
[Internal bug] [Bank] | Organization problem in the materials bank |

### ISSUE THREAD

**Issue by AdaliussS** [holydeew/WoWHellgarve-Legion#161]
![WoWScrnShot_112722_170450](https://user-images.githubusercontent.com/120292033/206886423-4b03c6e7-99d3-457a-a2a3-884e500be346.jpg)
![WoWScrnShot_112722_170502](https://user-images.githubusercontent.com/120292033/206886427-38a5b4c1-8e61-4e46-a47d-2e5f60148c0e.jpg)
When using clean up inside the material bank, it does not correctly order the materials, and uses the entire bank.
The correct thing would be that both the bank and the materials bank are 2 different things.
The Material Bank automatically stores materials and trade items for professions.
The bank is used to store all the desired materials, but the player must enter the materials as he pleases.

The bank of materials when you click Deposit materials, you must save the profession materials. Clicking Clear should organize all the materials into just the material bank.

In the photos that I have uploaded, you can see that one of the materials in the materials bank is missing, and is in the normal bank, since apparently the clean button makes the 2 banks join and does not organize them correctly, so perhaps it is a connectivity problem or perhaps a small error in the database and its connections. I hope I have helped. Good luck I hope you can fix the problem.
![image](https://user-images.githubusercontent.com/120292033/206886721-98d9c6f5-c6c3-40fd-8e04-5b48f7ff67d9.png)
![image](https://user-images.githubusercontent.com/120292033/206886749-619ebc1d-94ba-43fd-8c88-1b3ca9257e4e.png)

**Comment by skeezerbean** [comment]
Sending in a fix for this
