### ISSUE TITLE
[Spell] [Mage] [Zones] When using any stormwind teleport. sends you to stormwind but on the opposite side.

### ISSUE THREAD

**Issue by AdaliussS** [holydeew/WoWHellgarve-Legion#162]
The positioning of the character when being teleported is the opposite of what it should be. The first image shows how it is at the moment.
![WoWScrnShot_121122_004830](https://user-images.githubusercontent.com/120292033/206887121-96b3ff13-1a3e-4fd6-81f4-5bc54a9035a6.jpg)
The correct positioning would be this way, since the front portal is the one that takes you to the outside of the wizard tower in stormwind.
![WoWScrnShot_121122_004858](https://user-images.githubusercontent.com/120292033/206887151-39e50e34-d8b9-49a6-93ec-24d529a07726.jpg)

**Comment by skeezerbean** [comment]
I'm submitting a change that should put the Mage at this location (check mini map) when executing spell 3561 "Teleport: Stormwind" - this will be applied whenever I give changes to Holy for the Mage Class Hall

![image](https://user-images.githubusercontent.com/19826665/217337527-21b60489-e7ab-431a-83a9-9914f67d4c79.png)
