### ISSUE TITLE
[Spell] [Paladin] |Blessing of Higher Kings. does not reflect the shield on the character's hp bar |

### ISSUE THREAD

**Issue by AdaliussS** [holydeew/WoWHellgarve-Legion#163]
![image](https://user-images.githubusercontent.com/120292033/206887306-08d4405d-2f89-46d6-a9d6-7cc425b1b8a9.png)
The blessing of superior kings. It is an ability that consists of giving an ally a shield to yourself from a certain amount of damage (%attack power and %strength) and regenerates it every 6 seconds. In the photo that I have taken and edited very simply, you can see that even having the shield it is not reflected in the hp bar, the example above is a photo of another character, from another server, and how the shield should be reflected. shield on the hp bar.
I have tested in the interface part to rule out that the ability was not reflected due to a bad configuration.
I also don't know if the ability is really working and if it absorbs what it should.
![image](https://user-images.githubusercontent.com/120292033/206887587-756a060a-4999-4346-949f-80e661b2b2bd.png)

In addition to that, in some cases, having both paladin repression blessings active, this ability is usually deactivated.
Good luck, I hope you find the error and can fix it.

**Comment by skeezerbean** [comment]
It is absorbing. No idea if I can get it to reflect anything visual on the character or not.

![image](https://github.com/user-attachments/assets/7892bd4d-9a93-4030-ae90-f2cfc44915d3)

**Comment by skeezerbean** [comment]
To give a followup, if you are missing health then it will show a buffer in the HP bar of what is covered by any absorb amount. This seems to be the same across all spells I've looked at so far with the same ability.

![image](https://github.com/user-attachments/assets/3debfe33-93ba-413d-ae89-d1fd99b3f20f)
