### ISSUE TITLE
[Quest] [Krokul Refuge] From the dark | Quest= 46839  High Exarch Turalyon does not give the mission it stays in blue #164

### ISSUE THREAD

**Issue by Danort2023** [holydeew/WoWHellgarve-Legion#164]
The mission consists of walking with the high exarch Turalyon. But when he is going to give it to you, it stays in a blue question mark. And it doesn't let me continue with the progress of the Argus campaign and I got stuck. 
![image](https://user-images.githubusercontent.com/123770946/215183491-a1402481-38d6-4625-bf8e-d4ce8f992f6f.png)
I hope they can provide a solution. I send many greetings to the developer team.

**Comment by skeezerbean** [comment]
This is now fixed
