### ISSUE TITLE
Artifact Priest Discipline

### ISSUE THREAD

**Issue by Deadrock89** [holydeew/WoWHellgarve-Legion#168]
Within the discipline artifact mission chain, in the mission "a new threat" you have to find 3 clues using a crystal; It is evident that using Kalec's image crystal, the archmage appears, but he does not find the clues in the locations for it, for which the mission is not completed and does not continue the chain.

[https://www.wowhead.com/es/quest=41626/una-nueva-amenaza]
![WoWScrnShot_032623_185826](https://user-images.githubusercontent.com/114049513/227811059-684ac78a-bc6b-4004-9ea4-4e5303d3d075.jpg)

**Comment by skeezerbean** [comment]
Sent in a fix. It won't update using the crystal, but he summons when clicking any of the objects to speak about the one you clicked and give update. Should be live whenever Holy applies the update
