### ISSUE TITLE
Azuna bug (HellLegion)

### ISSUE THREAD

**Issue by ShadowmaneClan** [holydeew/WoWHellgarve-Legion#169]
In Azuna if you go to the Azure Repose (the place with Senegos) it seems that all the phases of it are active at once( the initial meeting, the withered invasion, and the part with the drained whelplings). Furthermore in Dalaran it seems that all the class hall intro NPCS are instanced as well and some of them are overlapping (I.E the Paladin, Hunter, and Demon Hunter instances at krassus' landing. Also Thrall in Dalaran for some reason)

**Comment by skeezerbean** [comment]
Azsuna will eventually get cleaned up through out its quest chains, but will take a long while to get to that point. Dalaran and class hall NPCs should be mostly cleaned up. Paladin stuff being applied soon, and just priest and shaman left after that. Anything else beyond that will need details of specific issues to look into
