### ISSUE TITLE
[Trinket] [151955] Kingaroth - NM/HM/Mythic Acrid Catalyst Injector

### ISSUE THREAD

**Issue by ScreamLock** [holydeew/WoWHellgarve-Legion#172]
The Current Behaviour is as following: The behavior is that trinket does not give any stat whether it is Haste, Mastery, Crit and when the trinket proc it gives nothing at all

Expected Behaviour should be as following: In 985 they give that https://imgur.com/a/7HTxhkN

Screenshot/Video (IMGUR/YOUTUBE): https://imgur.com/a/X9KOcaG

**Comment by skeezerbean** [comment]
Fix sent in for this
