### ISSUE TITLE
[Talent] [Spell = 155228] [Lone Wolf Hunter]

### ISSUE THREAD

**Issue by ScreamLock** [holydeew/WoWHellgarve-Legion#174]
The ID is : https://www.wowhead.com/spell=155228/lone-wolf

The Current Behaviour is as following: Talent lvl 15 "Lone wolf" doesnt work it does not appear in buff

Expected Behaviour should be as following: Have the buff and the damage must be up to 18% as written on the talent

Screenshot/Video (IMGUR/YOUTUBE): The first is talent https://imgur.com/a/an9vZYi
The 2nd is buff https://imgur.com/a/TOcIjYk

**Comment by skeezerbean** [comment]
![image](https://user-images.githubusercontent.com/19826665/232955114-b404af50-1129-4120-b36b-33512ca113d7.png)

This aura is on my player once I take this talent. At no point am I seeing an indication that it should show by the players nameplate. Your second image says it's the buff, and I do not see this buff in the image so I'm not sure what you're referring to.
