### ISSUE TITLE
[Quest][Idol of the Wilds] Satyrs dying don't triger the quest

### ISSUE THREAD

**Issue by AdetteVorthos** [holydeew/WoWHellgarve-Legion#179]
The 1st etape of the quest don't progress.
Kalazzius can early drop the Idol, but it can be given to end the quest.

https://www.wowhead.com/quest=42036/idol-of-the-wilds
https://www.wowhead.com/npc=106042/kalazzius-the-guileful

**Comment by skeezerbean** [comment]
![image](https://user-images.githubusercontent.com/19826665/233752297-b20b2c22-34f9-43d0-82ff-8873767631b0.png)

It updates just fine. It doesn't update on kill, it updates when their hp gets low and it isn't 100%, just like retail.

**Comment by AdetteVorthos** [comment]
Ok thanks, it sims that I got really unlucky, and Wowpedia and WoWhead state about killing.
