### ISSUE TITLE
Warlock destruction sceptre of sargeras bug

### ISSUE THREAD

**Issue by Alzrius** [holydeew/WoWHellgarve-Legion#183]
There's a bug when you do the main quest for warlock destruction, when you must pick up your sceptre to destroy the portal the lootbox opens and right after that an animation starts, doesn't leave you time to pick up your weapon and afterwards you can't reopen the loot to be able to pick up your sceptre. Here's the point in quest and what should happen: animation should start after you loot the sceptre, it starts after you open the box. 
https://youtu.be/fnQOvxkWYco?t=1406

**Comment by skeezerbean** [comment]
I sent in a fix for this so that the cutscene doesn't start until the item is looted rather than just clicking on the object. The altar won't respond until you have the item, and scene is advanced to a point after looting
