### ISSUE TITLE
(Quest ) druid tank weapon

### ISSUE THREAD

**Issue by Ulthalesh** [holydeew/WoWHellgarve-Legion#185]
I did the quest suites to get the druid tank artifact except that when I got to the ''Ursoc's lair'' scenario, I was stuck at step two

screen: https://imgur.com/undefined

Quest link :https://www.wowhead.com/quest=41468/mistress-of-the-claw     ( started quest )
                  https://www.wowhead.com/zone=7974/ursocs-lair   (scenario where we stuck)

**Comment by skeezerbean** [comment]
Screenshot link doesn't work - any other details?

**Comment by skeezerbean** [comment]
And to elaborate, I didn't find an issue with the scenario. I just went in at level 100 and ran through it, each stage updated fine. Re-open if you have more details or something specific that can cause an issue that you find
