### ISSUE TITLE
Warlock Class mount quest 

### ISSUE THREAD

**Issue by TheLastNoobb** [holydeew/WoWHellgarve-Legion#186]
https://www.wowhead.com/quest=46243/the-wrathsteed-of-xoroth
is bugged
After i Take the Quest The npc Teleports me to the Senario Instance 
but before the 7 Seconds teleportation Stun is gone i get teleported outside to dalaran

**Comment by skeezerbean** [comment]
Will send in a fix for this, and smooth out a ton of scripting in the scenario. It's still wonky, but able to be completed ok until cleaned up later
