### ISSUE TITLE
Demon Hunter Class Mount quest

### ISSUE THREAD

**Issue by TheLastNoobb** [holydeew/WoWHellgarve-Legion#189]
https://www.wowhead.com/quest=46334/to-fel-and-back
at the last stage i have to attack the mob again and once its low hp it will become friendly and ill have to ride on the mount 
But once i click on it i get bugged unable to make actions and the mob spawns again and starts dealing damage until i die and if i die and ress i get teleported and endlessly falling

**Comment by skeezerbean** [comment]
Will send in a fix for this in my next batch of fixes, not sure when it will be applied.
