### ISSUE TITLE
Bug Mision profesion encantamiento

### ISSUE THREAD

**Issue by HardAzkeel** [holydeew/WoWHellgarve-Legion#201]
there is a bug mission of enchantment profession

you have to take 4 objects from each elite but I only lot 3 and I am missing 1, it does not let me lot elite Oll'ison because the mission is not completed.

https://www.wowhead.com/es/quest=39923/hacia-el-n%C3%BAcleo

**Comment by skeezerbean** [comment]
Sending in a fix
