### ISSUE TITLE
Mage artifical qvest bug

### ISSUE THREAD

**Issue by Powersema** [holydeew/WoWHellgarve-Legion#202]
Qvest The Dreadlord's Prize is Bug .
I can take this qvest, but the boss is not in that dungeon

**Comment by skeezerbean** [comment]
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/bc8d1e8e-510d-4600-ac12-5f6d7a678cf6)

I'm not finding an issue. Can you provide any other details?
