### ISSUE TITLE
Turnabout Betrayal - Enchanting quest bugged

### ISSUE THREAD

**Issue by domdiego44** [holydeew/WoWHellgarve-Legion#206]
[Turnabout Betrayal] [Azsuna] https://www.wowhead.com/quest=39916/turnabout-betrayal

    [NPC] [Eredar Riftweaver] https://www.wowhead.com/npc=92450/eredar-riftweaver
    [NPC] [Felguard Invader] https://www.wowhead.com/npc=92445/felguard-invader
    [Spell] Not Avaiable
    [Npc] Not Avaiable

After doing 2 sweeps in the zone, i got the following result: 4 [Congealed Felblood](https://www.wowhead.com/item=132199/congealed-felblood), 127 [Sticky Volatile Substance](https://www.wowhead.com/item=132204/sticky-volatile-substance), 121 [Demonic Runestone](https://www.wowhead.com/item=138817/demonic-runestone), several https://www.wowhead.com/item=138781/brief-history-of-the-aeons and https://www.wowhead.com/item=138782/brief-history-of-the-ages, but absolutely NO Fel-Crusted Rune https://www.wowhead.com/item=137286/fel-crusted-rune .
So impossible to complete. Quest bugged.

**Comment by skeezerbean** [comment]
Sent a fix in May, apparently forgot to close this
