### ISSUE TITLE
Warlock Hall quest

### ISSUE THREAD

**Issue by eloktar** [holydeew/WoWHellgarve-Legion#215]
- [Misión]Rebuilding the council (https://www.wowhead.com/quest=40823/rebuilding-the-council))
- [NPC] Hitssyn Flamescowl<br>

When i try to cast Soulstone on him to rezz him it says Invalid Target so i can`t complete the quest.

**Comment by skeezerbean** [comment]
You don't cast a soul stone on him, you right click his corpse and it resurrects him that way.
