### ISSUE TITLE
`[Quest] Archmage Vargoth's Retreat`

### ISSUE THREAD

**Issue by ManaInfectedRP** [holydeew/WoWHellgarve-Legion#216]
Bug Description: 
After teleporting to the top of the tower in Dalaran to go to Vargoth's retreat and pick up all the items in his room Archmage Kalec does not allow you to talk to him to complete the quest and continue with the next quest after.

[Quest] - Archmage Vargoth's Retreat
https://www.wowhead.com/quest=42423/archmage-vargoths-retreat

Here is a video of how it is supposed to work.
https://www.youtube.com/watch?v=etWbYShqVLE

Here is a video of how it's currently working:
https://youtu.be/4NXWJyrkJ04

**Comment by skeezerbean** [comment]
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/5d7fa6b0-8f5f-4ca2-9546-2e371ae87b85)

Holy re-applied some updates that didn't seem to fully take affect, and this seems to now be working fine
