### ISSUE TITLE
Trade Prince Gallywix - Goblin Questline bug

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#218]
**Bug Report - Goblin Questline is impossible because of the Trade Prince Gallywix (35222)**

**Date : May 19, 2023**

**Bug Description :**
During the quest _The Uninvited Guest (14116)_, We take the quest and we have to valid it at the _Trade Prince Gallywix (35222)_ up stairs of the building, except this one does not appear having the quest.

**Expected result :**
The quest _The Uninvited Guest (14116)_ is taken from _Sassy Hardwrench (34668)_, after that we need to run upstairs and meet the _Trade Prince Gallywix (35222)_, at who we rewarded the quest, and take another one from him nammed  _A Bazillion Macaroons ?! (14120)_ who is rewardable at _Sassy Hardwrench (34668)_.

**Observed Result:**
The quest _The Uninvited Guest (14116)_ is taken from _Sassy Hardwrench (34668)_, after that we need to run upstairs and meet the _Trade Prince Gallywix (35222)_. But it appear that the quest is not rewardable by Gallywix, he have a discusion, (just a greeting) and no finished quest for us. On the map, the questline appear clearly to be on Gallywix and no one else.
**With the help of Ursken**, we rewarded the quest and it apprear, that the new quest, nammed _A Bazillion Macaroons ?! (14120)_, is also impossible to pick up from the _Trade Prince Gallywix (35222)_. Ursken so, give it to me manually and after that, i rewarded correctly the nexts quests.

+ It appear that all quest bind to the _Trade Prince Gallywix (35222)_ is unrewardable. and so the quest _Life Savings (14126)_ is also impossible to be reward from Gallywix.

**Bug Impact:**
This bug has a significant impact on the gameplay experience of others players who want to create a goblin, this bug literally block the good creation of a goblin. and make it **impossible to finish the questline, and so, a goblin.**

**Bug Reproduction:**
The bug has been successfully reproduced. _You just need to create a goblin and do the questline. At some point you gonna have this issues._

NPC in cause :
_Trade Prince Gallywix (35222)_

Quests in cause :
_The Uninvited Guest (14116)_
_A Bazillion Macaroons ?! (14120)_
_Life Savings (14126)_

**Comment by skeezerbean** [comment]
Fixed, NPC had a wrong flag (didn't flag NPC for quest turnin/giving) set on this server and is now corrected.
