### ISSUE TITLE
[Quest] [Demon Hunter Campaign] The Invasion of Niskara.

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#223]
**Link WoWhead** : https://www.wowhead.com/quest=42920/the-invasion-of-niskara

**ID Quest** : 42920

**What is the problem ? :** The first thing we need for this quest is "Control Console activated", but when you click on it, absolutely nothing happens. No portals open, so we can't complete the rest of the quest.

**Consequences ?** 
impossible for demon hunters to finish their campaigns without going through the "GM Ticket". And at the same time to accomplish the Legion flight achievement.

**Comment by skeezerbean** [comment]
Sent in a fix for this, and some followup quests
