### ISSUE TITLE
[Quest] [ItemQuest] No bones about it.

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#224]
**ID quest** : 45296

**WoWhead link** : https://www.wowhead.com/quest=45296/no-bones-about-it

**How do you obtain the item** : When you kill Nightbane, u receive [Charreid Bone Fragment], the item for the quest.

**Problem** : u Need To return the quest To an NPC : Mage Darius, he is normally in front of the raid Enter. But nothing.

**Comment by skeezerbean** [comment]
Sent in fix to add missing NPC outside dungeon entrance
