### ISSUE TITLE
**Link of The quest** : https://www.wowhead.com/quest=42006/a-new-threat

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#227]
**Link of The quest** : https://www.wowhead.com/quest=42006/a-new-threat 

**Problem** : unable to retrieve clues.

**description** : 

We must go to Dragonblight in order to retrieve clues in the Azure Draconic Sanctuary, the problem is that after having retrieved one of the 3 clues (several are available, but only one functional) impossible to continue the quest because none problem other clues present cannot be picked up.

**Consequences** : series of quests to unlock the Discipline Priest's prodigious weapon, without this quest, it is impossible to obtain the weapon.

_Originally posted by @Novrainn in https://github.com/holydeew/WoWHellgarve-Legion/issues/226_

**Comment by skeezerbean** [comment]
Fix was sent in for this, and crystal disabled to summon Kalec through it and only works through the objects in Dragonblight. Video posted to QA
