### ISSUE TITLE
Quest=48271;  Recovering the Pieces

### ISSUE THREAD

**Issue by fedemaster36** [holydeew/WoWHellgarve-Legion#229]
Description
The fragment you found is only one part of the key. I fear the other pieces have fallen into the hands of these ethereal beings you speak of... the Shadowguard. We must recover them all. The Shadowguard leaders and lieutenants in and around the Seat of the Triumvirate may well have the fragments in their possession. Get those key fragments, <name>... any way you have to.

Problem: When entering the dungeon and killing the npcs they don't drop the quest items, I already tried different difficulties and they don't drop them on any. 

YouTube link: https://www.youtube.com/watch?v=BTwQt9fU-hw&t=5s

Source k: https://www.wowhead.com/quest=48271/recovering-the-pieces

**Comment by skeezerbean** [comment]
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/60934de8-a5a2-46fe-891b-16ed04c0d116)

They dropped just fine at this location, and you can find all NPCs they should be dropping from here - https://www.wowhead.com/item=152201/armory-key-fragment
