### ISSUE TITLE
[Spell] [Monk] UB - "Infinite" Healing

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#231]
**Bug Report** - Monk Class : "Soothing Mist" (193884)

**Date :** June 3, 2023

**Bug Description :**
The Soothing Mist has been found to be the subject of an _annoying_ bug, in fact when a monk applies the spell to an ally and the disconnects **during** the casting of the spell, this one by deconnection - reconnection will _always_ have the spell on him and will even be able to **go everywhere in the world while concerning this one.**

Here we can see **Zerrax** with Soothing Mist, without the caster around him, and being healed.
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/71525f56-94e9-4e08-bfae-5e12ed17c929)

**Steps to reproduce the bug :**
```
Select a Monk character and make sure they are high enough level to have access to the "Soothing Mist".
Heal someone with the Soothing Mist.
While healing, the person need to deconnect and reconnect.
After that, the personn keep having the spell on him.

NB : it appear to be infinite, but in reality it's just timed with the duration spell. (it's not infinite, just really looong.)
```

**Expected Result :**
The Soothing Mist must not continue after disconnection.

**Observed Results :**
> The Soothing Mist, after deconnection of the healed, keep after reconnection, and is kept at any distance of the caster.
> The Caster when the healed is disconnected. stop his casting and can re-use this spell on him, and do the same thing.
> This spell is not stackable and is applied to the caster. (i mean, using "Summon Jade Serpent Statue" (115313) do not multiply the Soothing Mist auras on the healed)
> The Spell is not Infinite.
> The Spell is decast after entering in a arena.
> This don't work in other sens. (When it's the monk who disconnect, the spell is not kept.)

**Bug Impact :**
This bug has a **significant impact** on the gameplay experience. It can be used **for pexing**, healing someone at the start of a dungeon to help him, or in Savage PVP.
We can also imagine **some monks** (like 5, 6 monks) using Soothing Mist on 1 guy and being invincible.

**Bug Reproduction :**
The bug has been successfully reproduced **several times** with the help of **Zerrax**, we discover also some features of this bugs, but nothing so dangerous than that.

**SPELL ID(s) :** 115175 - Soothing Mist

**Video :** https://youtu.be/P2CoB1RHS4Q

Player who helped me : **Zerrax**

**Comment by skeezerbean** [comment]
Sending in a fix that forces removal of this aura on login
