### ISSUE TITLE
[Bug] [/RW (Raid Warning)] The /rw don't work !

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#240]
**Bug Report :** Raid Function : Raid Warning (/rw ()]

**Date :** June 07, 2023

**Bug Description :** When in raid you try to create a raid warning by the function /rw.

the chat trun correctly in "Raid Warning".
> ![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/024ca672-ec4a-405b-ab6c-70eb9fef6529)

But when you write something and press "enter", the message is not send. and nothing appear in front of your screen.

**Comment by skeezerbean** [comment]
This is now working.
