### ISSUE TITLE
[Bug] [Trinket Stats] A fraudulent trinket who don't give good statistics è_é

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#242]
**Bug Report -** Statistics problem with a trinket.

**Date :** June 11, 2023

**Bug Description :** 
Ok, so i notice a problem with my stats when i equipped a particular trinket.

In fact my trinket "Eye of Shatug" (152645) who are ilvl 960 Mythic, give me more HP than my same trinket, but with an ilvl of 1300.

**Here the evidences**

We can see right here that my trinket put me **at 61M HP** with his stamina (here Endurance) stats.
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/3b5d7016-228f-4a53-922c-d7dc63161190)

Now, here we can also see that same trinket, ilvl 1300, with more stamina, but i have less HP !! **I have 60M**
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/c68d3294-4e64-4a1c-a9f8-328cf591d0a4)

We can notice so that my trinket ilvl 1300 **don't have functional statistics**. and that's embarrassing, because i **paid 325 Donor Point** to have this trinket D:

+ plus,
> I obtain this trinket by enchantment at the Clerc Maluuf, the disclaimer said that if i enchant the item it can don't work, but here is not the problem. it work, but the stats don't follow the ilvl !

**Bug Impact :**
Heavy. It have a heavy impact on the PVE gameplay. If people see that, enchant their item by spending money in the game, it will be a disaster to see that our item is clearly ilvl 1300, but not their real stats !

Thanks for reading.

**Comment by Gueryghembal** [comment]
/!\ NOTE /!\

After testing some bonus id i notice something else :

> In fact the bonus id of the trinket goes "too far" and is capped at 1300 when the item should be ~1330 ilvl
> 
> So the stats, from just over 1300, like 1301 or 1302 and over, is disable and restart at 0 
> 
> So you must use a bonus id of the same kind , but less powerful, but enough for the item to be JUUUUUST 1300, and the stats will work.

So it's not the 400+ ilvl from the clerc maluuf that has a problem, it's the item we want up, the slightest +400ilvl on a minimum 901 item ends up with canceled stats

The maximum ilvl for the +400 to work is ilvl 900, if you increase an ilvl 901 with +400, his stats will be canceled !

**Comment by Novrainn** [comment]
I also add that the jewel itself when used does not work.
The Eye of Shatug/F'harg are linked together, the use of one of them transforms it into the other (for example: the eye of F'harg becomes Eye of Shatug if it is used, if everything works normally). Except that here, neither of them change if we click on "Use" they remain the base eye.

**Comment by skeezerbean** [comment]
Any ilvl over 1000 likely will be bugged, so if this is an issue when this item is ilvl 1000 then please give some more details.
I'll look into the use of the item swapping between modes and see what I can find.

**Comment by skeezerbean** [comment]
A fix is being sent in for this
