### ISSUE TITLE
mision bug sastreria 

### ISSUE THREAD

**Issue by HardAzkeel** [holydeew/WoWHellgarve-Legion#244]
I wanted to report a missing tailoring mission bug. 

https://www.wowhead.com/es/quest=46679/el-hilo-de-las-sombras

the npc is there but does not give missions

**Comment by skeezerbean** [comment]
This NPC has over 20 quest assigned to it, and the flag is enabled to be a quest giver. If you don't see a quest then you don't meet the prerequisites. If there is a specific quest you need then read through wowhead notes to make sure you meet requirements for it.
As for tailoring this NPC only offers a few. The rest are blacksmithing or Leatherworking, and some weren't available until after Legion.
