### ISSUE TITLE
[Report] [Eonar, Food, Argus's chest]

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#245]
**Date :** June 14, 2023

**Report Description :**
Hello ! With the help of **Yassoux** we tried some fixes applied on the PTR

The list of the test :
> The Enoar Skip
> The Mage's Food in arena.
> The Argus's chest lootrate

- **Eonar Skip :**
    The skip work very well, the sheep force us to use the spell Life Force as expected, the paraxis die before eonar, that's perfect !
    If we kill the sheep the boss is not killed as expected.
    
- **Food 1v1 :**
    The Mage's Food in arena is correctly spawnable, takable, and usable, the only problem that we have is, when you use the food, the heal grant by the heal is not instant, it start 7 seconds after the usage, the spell have a duration of 20s, the heal start at 13s.
    And it's not normal.
    
- **Argus's chest & Lootrate :**
    For the Argus's chest, we tried twice the entire raid, with clean way, we did every boss, with normal conditions, in Mythic Mode, but there is absolutly CERO loot, nothing, nada, rien, quetchi, R, Even if there are a loot incrase on the chest, we can't sens it because of the loot that just don't appear...
    Some people have loot, some other don't, and we keep not undersanding why, it's not the leader who loot, it's not the members of the raid, we can have 1 chest per week, per characters... ... incomprehensible
    
```
Antorus ID(s) :
Essence of Eonar, 122500
The Paraxis, 124445
Eonar Battle Helper, 150000
Argus the Unmaker, 124828

Object ID :
The Gift of the Pantheon (the chest), 277355
Refreshment Table (Mage), 211363

Item ID : 
Conjured Mana Pudding, 80610

**Comment by skeezerbean** [comment]
When you say mage food in the arena, what are you referring to? Or is this just the top conjured normal food from mage?

**Comment by skeezerbean** [comment]
When doing Argus earlier, and Eonar weeks back with some changes, chests seem to have loot now from some previous fixes. The pantheon item also upgrades some of the trinkets now as well. Re-open if you can give more details if something is still broken
