### ISSUE TITLE
Bug in Return Fire quest

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#246]
Quest Link: https://www.wowhead.com/quest=13853/return-fire
Problem:  I need to use astraanar thrower to shot down wind riders but... i can't use it. My cursor doesn't change and click on it don't work.
![Screenshot_4839](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/e76451c4-24fb-441b-be11-5ba0ed07762a)

**Comment by skeezerbean** [comment]
Sent in a fix to correct the PhaseId's for the throwers
