### ISSUE TITLE
Bug in "King of the foulweald" quest.

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#247]
Link: https://www.wowhead.com/classic/quest=6621/king-of-the-foulweald
Problem: Too much furbolgs mobs spawn and they killing me in seconds. Around 13 furbolgs spawned once and attack in the same time.

**Comment by skeezerbean** [comment]
The script for this spawns adds spread out over 3 minutes. I am submitting some changes that doesn't spawn 2-3 at the same time, but they DO pull nearby enemies if they are in range. They definitely do not spawn 13 at once.
