### ISSUE TITLE
[Quest] [Discipline Priest Campaign] Away from Prying Eyes

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#248]
**ID of The quest** : 44782
**link Wowhead** : https://www.wowhead.com/quest=44782/away-from-prying-eyes

**description** : We need to go to the Violet Room to join the Council of Six. the problem being that we are supposed to make a portal appear to enter it but nothing comes. I tried this quest in the test and live server and nothing helps the problem is the same and no NPC offers me to continue the quest. this quest as well as the questline is required to access the mage tower challenge. After this quest is supposed to come after the start of the solo campaign for each specialization, except that we receive the quest from the start without having to do the other which blocks us once the mages' tower is within our reach: it is currently built, but the warmage does not offer me any quests despite my smug nether shards

**Comment by skeezerbean** [comment]
This requires sniff data. Ddraig is working on this but may take a while in retail to get all info. Nothing will happen with this until then.

**Comment by skeezerbean** [comment]
I sent a generic bypass for this, a portal that appears at the top of the stairs and will teleport you up and give credit. It's on my list to script fully once I get all of the data for it
