### ISSUE TITLE
[Quest] [Priest Campaign] In dire Need

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#249]
**Link** : https://www.wowhead.com/quest=44821/in-dire-need

**Problem** : We have to listen to the advice of the spoken Six, except no NPCs offer special bubbles and nothing happens.

**Consequences** : Quests Required to Unlock the Mages Tower. So we cant do the MT.

**Comment by skeezerbean** [comment]
Depends on Prying Eyes, see https://github.com/holydeew/WoWHellgarve-Legion/issues/248 for more details. Will update once we have more info

**Comment by skeezerbean** [comment]
Quest can be accepted, an NPC nearby will auto complete every 10s until I get more data to script the scene. Now can be completed without GM. On my list to script once I have sniff data.
