### ISSUE TITLE
[Raid] [Tomb of Sargeras] [Loot] Kil'Jaeden chest dont Give loot.

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#250]
**Problem** : 

Same problem as on Argus The Unmaker, the loot box does not take into account the loot put in free access, it simply gives us gold coins. I don't know if it can give loot, personally I've never had any.

**Comment by skeezerbean** [comment]
Fix has been sent in for this and will need tested, not sure when admins will apply it
