### ISSUE TITLE
[Quest] Leave no man behnid

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#260]
Link to quest: https://www.wowhead.com/quest=25809/leave-no-man-behind
Character name: Yenin
Issue: All npcs in minecarts are dead and i can't make this quest bcause of this. I can't click on them or anything. 
![Screenshot_4902](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/a285ad4d-eeb9-4357-8889-b04e11bbf2f4)

**Comment by skeezerbean** [comment]
Sent a fix to admin
