### ISSUE TITLE
[Quest] To the Rescue

### ISSUE THREAD

**Issue by Aizen26** [holydeew/WoWHellgarve-Legion#264]
Link: https://www.wowhead.com/quest=13712/to-the-rescue
Character Name: Aizen
Issue: NPC Kadrak doesn't appear in Splintertree Post after the Kodo Brutusk is dead
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/137589309/ab1097d8-f998-4593-8a35-53c5983e92eb)

**Comment by skeezerbean** [comment]
Sent in a fix
