### ISSUE TITLE
[QUEST] Downfall

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#266]
Link: https://www.wowhead.com/quest=25848/downfall
Character name: Yenin
Problem: Chest from horde general don't drop insignia
![Screenshot_4937](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/a65f985f-729d-4556-8aa1-d1c3e4683983)

**Comment by skeezerbean** [comment]
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/a979969c-825c-44fb-9ac4-47f7bff66760)

Seems to be dropping, but not 100% like it should. Something seems broken with the object and cannot get it to have loot consistently, but sending in some changes that should at least help some
