### ISSUE TITLE
[Quest] Nothing a Couple of Melons Won't Fix

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#267]
link to quest: https://www.wowhead.com/quest=14193/nothing-a-couple-of-melons-wont-fix
Character name: Yenin
problem: Melon laying on groun don't give you a melon
![Screenshot_4951](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/1311562f-c8d5-44c3-acd8-d561f3e9791a)

**Comment by skeezerbean** [comment]
Sent in a fix
