### ISSUE TITLE
[BG] [Silvershard Mine] - Minecart

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#273]
**Bug Report :** Silvershard Mine the minecart is !! fast !!

**Date :** July 01, 2023

**Bug Description :**
When you enter the bg Silvershard Mine, the Mine Cart immediatly running without waiting for the timer to start the BG.

As we can see right here, the timer is still here that the mine cart is already running.
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/4ee4ec79-ad22-4cca-9cfb-7aa893271d5a)

**Expected Result :**
The normal way is :
> You join the BG
> The waiting timer start.
> At the end of the timer (start bg) => The Minecart spawn.

Player(s) who helped me : Zerrax, Nøvrain & Ursken.

**Comment by skeezerbean** [comment]
I'll be sending in a fix, was able to force them to wait 120 seconds before creating the mine carts
