### ISSUE TITLE
Spell : 68996 Two Forms 

### ISSUE THREAD

**Issue by EstaVendetta** [holydeew/WoWHellgarve-Legion#277]
Bug : After quest serie in Gilneas, i have obrain the Two Forms Spell , but i can't change to Worgen Form to Human Form.

https://www.wowhead.com/fr/spell=68996/deux-formes
https://www.youtube.com/watch?v=fPnDoMk2dOg

**Comment by skeezerbean** [comment]
I cannot reproduce this problem. After you finish the quest "Neither Human Nor Beast" you get the two-forms skill, and can switch between them. I went through this and had no trouble using it and switching.
https://www.wowhead.com/quest=24593/neither-human-nor-beast
