### ISSUE TITLE
[RAID] Antoran High Command Boss crashing the server

### ISSUE THREAD

**Issue by Muertador** [holydeew/WoWHellgarve-Legion#279]
Whenever attacking the 3rd boss of Antorus, Antoran High Command, on LFR/Normal/Heroic difficulty, the server crashes, I can beat it fine on mythic

**Comment by Muertador** [comment]
EDIT: Seems to only be a problem with my Hunter Cazzador, happens even on mythic now

**Comment by skeezerbean** [comment]
Do you have any other details on this, such as what specifically seemed to crash?

**Comment by skeezerbean** [comment]
No other details given, cannot reproduce. Closing.
