### ISSUE TITLE
[Quest] Cenarius, Keeper of the Grove

### ISSUE THREAD

**Issue by Gramzolo** [holydeew/WoWHellgarve-Legion#281]
**Link to the quest:** https://www.wowhead.com/quest=40122/cenarius-keeper-of-the-grove

**Quest ID:** 40122

**Character:** Miskov

**Issue:** Not able to return the quest to Malfurion Stormrage.

![q1](https://github.com/holydeew/WoWHellgarve-Legion/assets/139180700/f41b0c90-8fb6-4c97-bcad-56b4d6a450ea)
![q1_1](https://github.com/holydeew/WoWHellgarve-Legion/assets/139180700/a466131e-c2b2-49ae-a568-3ded7a6db040)                 ![q1_2](https://github.com/holydeew/WoWHellgarve-Legion/assets/139180700/6be0b482-a1e2-46b1-83c8-2c99e454592d)

**Comment by skeezerbean** [comment]
Just tested in Hellgarve, and works fine. You need to talk to Malfurion where you get the quest, tell him you're ready and ride on him to the turn-in location. See videos on wowhead if needed.
