### ISSUE TITLE
[Enhancement Shaman] [Artifact] [Quest] The Hammer in the Deep

### ISSUE THREAD

**Issue by SaladGuy42** [holydeew/WoWHellgarve-Legion#282]
Quest link: https://www.wowhead.com/quest=40224/the-hammer-in-the-deep
Bug: Therazane doesn't have a option to open a portal to enter the crumbling depths. Manually entering the location gives the old phase so i guess this is a seperate instance.

**Comment by skeezerbean** [comment]
Shaman is disgusting, you should be ashamed of yourself. 💯 

But I'll get around to the whole class hall cleanup and artifacts eventually.

**Comment by skeezerbean** [comment]
A fix has been sent in for this, and a portal will be at Therazane phased once you have this quest. Missing quests and NPCs to unlock this are also added and scripted.  Whenever this fix gets applied by admins then should be good to go.
