### ISSUE TITLE
Quest: Short Circuit - https://www.wowhead.com/quest=40880/short-circuit

### ISSUE THREAD

**Issue by domdiego44** [holydeew/WoWHellgarve-Legion#284]
[Short Circuit] [Ratchet] https://www.wowhead.com/quest=40880/short-circuit
Action: https://www.wowhead.com/npc=102834/talk-to-chief-engineer-foote-in-ratchet

Can't complete, you can right click him, and select "I'm looking for information about the Inventor of Blingtron", but nothing happens. No talk back, no animation, nothing.

**Comment by skeezerbean** [comment]
Sent in a fix for this
