### ISSUE TITLE
Emerald NIghtmare :Felwort Mastery.

### ISSUE THREAD

**Issue by PokeUrEyeOut** [holydeew/WoWHellgarve-Legion#285]
https://www.wowhead.com/item=136413/seed-of-corruption#comments

After running this quest many times for the alchemy questline, "Seed of Corruption" item did not drop. I sat and waited for a few moments to see if maybe it dropped near boss.

Usually only recieved gold from the chest, if the chest was even clickable during said run through.

**Comment by skeezerbean** [comment]
Sending in a fix for this
