### ISSUE TITLE
[Quest][Hillsbrad Foothills] A Blight Upon the Land https://www.wowhead.com/quest=28237/a-blight-upon-the-land

### ISSUE THREAD

**Issue by TwistedBane** [holydeew/WoWHellgarve-Legion#286]
Zone - Hillsbrad Footils, realm - Sargeras, Legion, this is the last quest of the Sludge fields quest line, the issue is the Item needed to complete the quest (Head of Warden Stillwater) doesnt drop, I tried 3 times with no success.

**Comment by skeezerbean** [comment]
Sent in a fix for this
