### ISSUE TITLE
[Item] Acryd Catalytst Injector

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#287]
**Date** : 15 july 2023.

**Report description** : 
The Acrid Catalyst (Item ID : 151955) Injector is a trinket that increases our stats. Depending on our attacks, it increases either our Mastery, our haste or our critical score (the number depends on its ilvl, in 960, as specified on the screen, it increases the stats by 214) it is cumulative up to 5 times . Once a buff reaches 5 they reset to provide a bonus that stacks all three stats, here too the number depends on its ilvl, here in 960 it's supposed to be 2442.

The problem here is that everything works normally, except for the buffs.
They literally don't give anything, on the screenshots we can see that each buff is telling us "Mastery/Hate/Crit score increased by 0" and even looking at my stats they don't move, which means I actually get 0 trinket bonuses.
They stack well up to 5, and reset once they reach 5, but no stat bonuses are passed on to us

Here is the screenshot :

![WoWScrnShot_071223_132041](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/039511bf-123f-4311-934d-dc69ed46cdbe)
![WoWScrnShot_071223_132103](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/22c58b11-1d00-469e-bc47-77d99844d6ab)
![WoWScrnShot_071223_132102](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/f5eb9fb5-172b-494e-b891-5d3aab92d599)
![WoWScrnShot_071223_132110](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/ff513771-b284-4859-b1f0-c845f998b3aa)
![WoWScrnShot_071223_132341](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/30326a95-7820-4d38-8bbd-9c43ced118ce)

**Comment by skeezerbean** [comment]
Fix sent in
