### ISSUE TITLE
Suramar Bug Mission

### ISSUE THREAD

**Issue by HardAzkeel** [holydeew/WoWHellgarve-Legion#288]
Good gm
I'm going to report a bug mission of an NPC in Suramar that doesn't appear, in order to continue the Suramar mission chain.

https://www.wowhead.com/es/quest=44845/romper-un-brazo

**Comment by skeezerbean** [comment]
I cannot reproduce this. If I have the quest, the NPC is visible at the location shown on the wowhead link and can be killed.

To turn it in, this NPC is phased after you have quest (Take me to your Leader) 40391 or 40632 depending on your faction. It's possible the quest order is broken, but those are what is needed. This should be the same NPC that gave you this quest as well, so should be visible.
