### ISSUE TITLE
Quest 43487 doesn't work 

### ISSUE THREAD

**Issue by Mirayne** [holydeew/WoWHellgarve-Legion#29]
Can't complete a quest, book don't drop, all difficulties has been checked and item=139445 don't drop.

**Comment by asd1488** [comment]
> Can't complete a quest, book don't drop, all difficulties has been checked and item=139445 don't drop.

Please use the full link to the quest and the item:

`https://www.wowhead.com/quest=`

**Comment by skeezerbean** [comment]
Have a fix, sending to Holy
