### ISSUE TITLE
[Quest] In The outhouse

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#290]
Link to quest https://www.wowhead.com/quest=25524/in-the-outhouse
Character name: Yenin
Problem: In quest "In The outhouse" I can't use pirate's crowbar on submerged outhouse
![Screenshot_5077](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/c9d73281-d22e-4dba-b208-c0b1d7b24ba4)

**Comment by skeezerbean** [comment]
Sent in a fix for this
