### ISSUE TITLE
[Bug] Court of Stars: Talixae Flamewreath

### ISSUE THREAD

**Issue by Narovoid** [holydeew/WoWHellgarve-Legion#291]
**Bug Report - Killing Enforcers to pull adds away from the boss doesn't work properly**

**Date - 7/17/2023**

**Bug Description;** 
When killing enforcers in mythic before Talixae Flamewreath, the adds that she has with her do not get told to go investigate, pulling the add away to be killed by players as its intended and designed.

**Steps to Reproduce** - 
Do the dungeon on mythic difficulty, do not move any of the enforcers from their position to a new position. Kill them as they are and make sure you are not using any GM or admin commands to alter the dungeon in anyway.

**Expected Result:**
Killing Enforcers will pull the adds away from the boss, allowing the player to kill the boss and progress the instance.

**Bug Impact:**
I have found this bug does impact the players often because this could happen on normal or heroic difficulty as well. As a big enjoyer of M+, I find it frustrating when I know the dungeon isn't working properly and I cannot progress and complete the instance. Instead I have to spend more time failing the instance and downgrading my keystone down a level.

![WoWScrnShot_071723_185309](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/72abd00e-2e15-44a3-9f21-f47f58bdaf2c)
![WoWScrnShot_071723_185305](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/e13bc10c-6769-491f-8d46-585230fc264a)
![WoWScrnShot_071723_185232](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/e8b3cad2-fe9c-40d1-9895-ae6b88a74d90)
![WoWScrnShot_071723_185229](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/716f1c0a-9f4b-4437-9f85-db3d4452efbb)
![WoWScrnShot_071723_184959](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/e430d0e3-fde5-456a-8dee-cf42e4c15306)
![WoWScrnShot_071723_184928](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/24c16e81-c5ff-4893-8742-716edd123879)
![WoWScrnShot_071723_184906](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/f96d2952-fd4d-4b60-81b4-161fac9828cf)
![WoWScrnShot_071723_184903](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/d4eb47a9-1784-46a6-aa83-d35fe33fd275)
![WoWScrnShot_071723_184858](https://github.com/holydeew/WoWHellgarve-Legion/assets/70707424/5dff69fa-9ba4-4277-bbec-05c01741ce17)

**Comment by skeezerbean** [comment]
Submitted fix that should still have these respond even if you pull them back further
