### ISSUE TITLE
[Quest] The Acient Braizer

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#292]
Link to quest: https://www.wowhead.com/quest=25762/the-ancient-brazier
Character name: Yenin
Problem: I can't use splithoof brand on ancient braizer
![Screenshot_5082](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/cb093999-e1b1-4b7a-86c8-3571755c5311)

**Comment by skeezerbean** [comment]
Sent in a fix for this
