### ISSUE TITLE
[Location bug] Thousand Needles

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#293]
Location: between darkcloud pinnacle and freewind post in thousand needles
Character name: Yenin
problem: On one of bridges and two hills in that place is bug that killing me instantly. I can't make quest in this place bcause of this
![Screenshot_5089](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/3733ff81-82ad-441c-b13a-dd8065549985)
![Screenshot_5088](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/ee10ce30-7afd-46ac-88bb-5f1a062b1b13)
![Screenshot_5087](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/cb91a94a-c92a-49f7-80f3-85074fec1cb2)

**Comment by skeezerbean** [comment]
Sent in a fix for this
