### ISSUE TITLE
[Quest] Grimtotem Chiefs: The Chief of Chiefs

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#294]
Link to quest: https://www.wowhead.com/quest=27327/grimtotem-chiefs-the-chief-of-chiefs
Character: Yenin
Issue: This enemy npc have ability called "Chieftans call" that summon more nemies but he spawns big amout of this enemies. All of this enemies have 8k hp and i can't kill main boss bcause i need to escape.

**Comment by skeezerbean** [comment]
Sent in a fix for this. Apparently he had scripting setup, but wasn't enabled to use it, so he spammed his abilities to summon the helper NPCs. It can still be very difficult (it's supposed to be), but it IS doable once the fix is applied.
