### ISSUE TITLE
[Quest] The Doomstone

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#295]
Link to quest: https://www.wowhead.com/quest=28159/the-doomstone
Character name: Yenin
issue: I can't drop the doomstone from Animus. I tried 4-5 times in row but theres nothing. 
![Screenshot_5092](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/86e5fb19-03ad-4b8f-aee2-6cb203daf561)

**Comment by skeezerbean** [comment]
Sent in a fix for this
