### ISSUE TITLE
Purple Lotus

### ISSUE THREAD

**Issue by KORDREVIX** [holydeew/WoWHellgarve-Legion#299]
Is a tipe of flower that don't appear in the world 
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/140178618/0cdef937-fd5e-4304-8200-dbb03d7041d9)

**Comment by skeezerbean** [comment]
There are 2 objects with this name, and both are in the world. Need more details, re-open the issue if needed. Which object ID? Which zone(s)?
