### ISSUE TITLE
Quest item is unlootable

### ISSUE THREAD

**Issue by Mirayne** [holydeew/WoWHellgarve-Legion#30]
https://www.wowhead.com/item=132738/heart-of-zin-azshari is unlootable.

**Comment by asd1488** [comment]
> https://www.wowhead.com/item=132738/heart-of-zin-azshari is unlootable.

`From the quest= https://www.wowhead.com/quest=40668/eye-of-azshara-the-heart-of-zin-azshari`

**Comment by skeezerbean** [comment]
This fix was sent in a while back, re-open if it still doesn't work
