### ISSUE TITLE
[Item] [Antorus, The Burning Throne] Trinket of the Pantheon + Blessing of The Pantheon.

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#300]
**Date** : Sunday 23 july 2023.

**Character** Masamune, Morsatrae and with the Help of Gueryghembal.

**Item ID** : 
Blessing of the Pantheon : 155831
Trinket of the Pantheon :

>  - 154176 (https://www.wowhead.com/item=154176/khazgoroths-courage)
>  - 154174 (https://www.wowhead.com/item=154174/golganneths-vitality)
>  - 154175 (https://www.wowhead.com/item=154175/eonars-compassion)
>  - 154173 (https://www.wowhead.com/item=154173/aggramars-conviction)
>  - 154177 (https://www.wowhead.com/item=154177/norgannons-prowess)
>  

###  **First Problem : Blessing of the Pantheon** : 
 
 
 *How is this supposed to unfold* : Each time you use your pantheon blessing on your pantheon jewel (out of the 5 mentioned above), you increase its ilvl by 5, up to a maximum of 1000. (The jewel starts at 940 ilvl).
 
 *But what's going on here?* : Even if we use the object as a statement, it does not change the ilvl of the jewel. By definition, this one does not work. (Video :https://youtu.be/rVr75n8fcmI)
 
 By definition, it is clear that the problem to be solved lies in the fact that the object must increase the jewel up to a total of 1000 ilvl.
 
 + I add the fact that we are supposed to loot blessings each time Argus is defeated, it's 100% drop rate, here, there is never any.
 
###  **Second problem : Trinket of the Pantheon** :

*How is this supposed to unfold* : We receive the jewel in 940 ilvl, this jewel NEVER PROC HIGHER; because to increase its ilvl, we have to use the blessings.

 *But what's going on here?* : The proc trinket in a higher ilvl, when it's not supposed to. For example, on my screenshots, I had the right to a gem proc in 955 and 945 ilvl, whereas it is supposed to be by default in 940, and not higher proc in ilvl.
 
 
![WoWScrnShot_072323_213543](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/ab7a9663-b982-4174-bb79-3e2ebe851dbe)
![WoWScrnShot_072223_143825](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/1c6ce537-5b8b-4d69-aa02-0addfa19427c)

**Comment by skeezerbean** [comment]
This item now works the way it is supposed to, and should be dropping from the chest now.
