### ISSUE TITLE
[Quest] Just trying to kill some bugs

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#301]
Link to quest: https://www.wowhead.com/quest=24953/just-trying-to-kill-some-bugs
Character name: Yenin
Issue: When i'm in the hive i can't detonate mind controlled swarmer
![Screenshot_5133](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/210cea3c-c287-4072-ad79-0fdb6d8852fb)

**Comment by skeezerbean** [comment]
Sent in a fix for this
