### ISSUE TITLE
[Quest] How to make meat fresh again

### ISSUE THREAD

**Issue by JapaneseDragon11** [holydeew/WoWHellgarve-Legion#302]
Link to quest: https://www.wowhead.com/quest=24697/how-to-make-meat-fresh-again
Character name: Yenin
Issue: I baited dino into pit with spikes, dino died but quest don't make any progres.
![Screenshot_5139](https://github.com/holydeew/WoWHellgarve-Legion/assets/136913056/41f1dc18-8a27-4b57-bd34-2b4548d82b8a)

**Comment by skeezerbean** [comment]
Sent in a fix for this. It was already working, but limited to a short range. It also updated all players in that short range, rather than the one who was aggrod. This should now be fixed.
