### ISSUE TITLE
Eine grausame Gleichung (40238))

### ISSUE THREAD

**Issue by JackTennesie** [holydeew/WoWHellgarve-Legion#304]
Hey guys the quest A Cruel Equation is a bit bugt

What's the problem (with details)
I accept the quest go to the crystal vault which I am supposed to destroy, he also does the animation but gives no progress no matter which of the 3 crystals I destroy the quest is in Krokun [Argus] 

How it's supposed to work
The quest should progress normally after the animation and then break and disappear.

Evidence you have (such as screenshots)
i have no Screenshots but the Link from the Quest.
https://www.wowhead.com/de/quest=40238/eine-grausame-gleichung

**Comment by Ursken** [comment]
Solved after deleting cache folder.
