### ISSUE TITLE
[Quest] A Royal Summons

### ISSUE THREAD

**Issue by Scubbaa** [holydeew/WoWHellgarve-Legion#305]
Date: 26 July 2023 

Character: Sipah - Lightforged Draenei Paladin 110

Quest: A Royal Summons - https://www.wowhead.com/quest=38035/a-royal-summons

Issue:
`Unable to turn in quest `

Started the quest from the Scouting Map NPC, I talked to Admiral Rogers in Dalaran. The quest proceeds to continue by giving me a letter. After reading the letter and heading to the portal from the Dalaran Room, I spawned in the Skyfire Airship and tried talking to Admiral Rogers in the control room only to unable to turn-in the quest.  abandoning and re-doing the quest proved to be of no use.

Image:
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/140568490/4755e64c-13b4-4e00-9724-50d3644aaa60)

**Comment by skeezerbean** [comment]
Sent in a fix for this
