### ISSUE TITLE
Quest items for Improving on History is unlootable

### ISSUE THREAD

**Issue by Mirayne** [holydeew/WoWHellgarve-Legion#31]
Quest items 139782 and 139788 is unlootable

**Comment by asd1488** [comment]
> **Quest items 139782 and 139788 is unlootable**
`**Item 139782=** https://www.wowhead.com/quest=43524/court-of-stars-literary-perfection`
`**Item 139788=** https://www.wowhead.com/quest=43525/vault-of-the-wardens-borrowing-without-asking`

**Comment by skeezerbean** [comment]
Sent a fix to Holy to apply, issue can be closed once applied

**Comment by holydeew** [comment]
thank you for your report, have a great day/night.
