### ISSUE TITLE
Quest: United as One

### ISSUE THREAD

**Issue by domdiego44** [holydeew/WoWHellgarve-Legion#311]
[Quest]: https://www.wowhead.com/quest=43397/united-as-one

Already deleted cache, and logged out/in. When the quest reaches the "Council of war heard", every time i get down the stairs, i'm imobilized and teleported back to  Dalaran. Impossible to do.

**Comment by skeezerbean** [comment]
I am assuming this is for Priest. I've got a fix ready to send in but will have to wait until the rest of Paladin fixes have been tested
