### ISSUE TITLE
[Quest] [Legion] Cenarius, Keeper of the Grove

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#315]
This Quest [Cenarius, Keeper of the Grove](https://www.wowhead.com/quest=40122/cenarius-keeper-of-the-grove) is bugged in that way, when you don't leave the pet and run with [Malfurion Stormrage](https://www.wowhead.com/npc=91109/malfurion-stormrage) or this [Malfurion Stormrage](https://www.wowhead.com/npc=91462/malfurion-stormrage) the quest won't get turnable, so you always need to repeat the quest and follow him at the same time. Coming later behind after he arrived at the point where he changes his NPC ID the quest won't get completeable.

So this Quest is working but not working at the same time. I have tried it in retail and it should be turnable even after you come like 20mins later to that point where he changes his NPC ID.

**Comment by skeezerbean** [comment]
Fixed so player gets updated when arriving at location regardless of being on vehicle
