### ISSUE TITLE
[NPC] [Item] Chieftain Graw

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#316]
This NPC [Chieftain Graw 91318](https://www.wowhead.com/npc=91318/chieftain-graw) should be dropping Item [Chieftains Beads 128340](https://www.wowhead.com/item=128340/chieftains-beads) after the first time you kill to start the Quest [The Chieftain's Beads 38146](https://www.wowhead.com/quest=38146/the-chieftains-beads) but it didn't drop. Loot Table from this NPC needs to get fixed.

You can see the loot drop chance from this NPC in his Wowhead [Link](https://www.wowhead.com/npc=91318/chieftain-graw#drops)

**Comment by skeezerbean** [comment]
fix sent in
