### ISSUE TITLE
[NPC] [Legion] Koda Steelclaw

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#317]
NPC ID = [91223](https://www.wowhead.com/npc=91223/koda-steelclaw) 

This NPC is missing at her original location like the same in Retail. NPC is outside of the Camp while it should be in the cave.

Those are the Quest the NPC has available 

[The Demons Below 38144](https://www.wowhead.com/quest=38144/the-demons-below)
[Out of the Dream 38145](https://www.wowhead.com/quest=38145/out-of-the-dream)
[Entangled Dreams 38147](https://www.wowhead.com/quest=38147/entangled-dreams)

Screenshot: [Location where she should be](https://imgur.com/a/GWnrw9P)

**Comment by skeezerbean** [comment]
Added missing points of this NPC, phasing, scripting for quests, and fixed quest order. Fix sent in
