### ISSUE TITLE
[Quest] [Legion] Entangled Dreams

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#318]
Quest ID: [38147](https://www.wowhead.com/quest=38147/entangled-dreams)

Quest is working as usually but the problem is, there is no [Bramble Wall](https://www.wowhead.com/npc=99032/kill-credit-open-bramble-wall) and when killing the needed [NPC Morphael 91045](https://www.wowhead.com/npc=91045/morphael) the Kill Credit shows some numbers with -minus and in the quest log it shows that the quest is not complete but you got the kill credit so when you go to the quest giver you can turn the quest in as usual 

[Video ](https://www.youtube.com/watch?v=t7OiW7njpZE&t) how this Quest should work

**Comment by skeezerbean** [comment]
Sent in a fix
