### ISSUE TITLE
[Quest] [Legion] The Corruptor

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#319]
Quest ID: [39384 The Corruptor](https://www.wowhead.com/quest=39384/the-corruptor)

Behaviour: Quest works as usually but the only bugged thing is when you kill the NPC [Kagraxxis 95320](https://www.wowhead.com/npc=95320/kagraxxis-the-corruptor) the Kill Credit shows some numbers instead of 1/1. The Questlog shows 0/1 kills even if you killed that NPC. Quest End [Evelle Nightwhisper 91650](https://www.wowhead.com/npc=91650/evelle-nightwhisper) shows a grey question symbol but you can end the quest as usually after killing [Kagraxxis 95320](https://www.wowhead.com/npc=95320/kagraxxis-the-corruptor)

[Video](https://www.youtube.com/watch?v=cGvl0A9nTbM) how the Quest should work like in retail

**Comment by skeezerbean** [comment]
Sent in a fix for this
