### ISSUE TITLE
[Quest] [Legion] Moist Around the Hedges

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#320]
Quest: [42857](https://www.wowhead.com/quest=42857/moist-around-the-hedges)
NPC / Object ID: [Moist Grizzlecomb](https://www.wowhead.com/object=251425/moist-grizzlecomb)

Behavior: Quest is not acceptable. [Moist Grizzlecomb](https://www.wowhead.com/object=251425/moist-grizzlecomb) is not clickable so there is no acceptable Quest 

Video: [Wowhead Youtube](https://www.youtube.com/watch?v=oyrYYFZEpis)

Edit: Quest is not working, like Quest items are not dropping or are pickable 
 [Moist Grizzlecomb](https://www.wowhead.com/item=138788/moist-grizzlecomb)

**Comment by skeezerbean** [comment]
Sent in a fix for this
