### ISSUE TITLE
[Quest] [Legion] Emerald Sisters

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#321]
Quest ID: [42748 Emerald Sisters](https://www.wowhead.com/quest=42748/emerald-sisters)
NPC: [108600](https://www.wowhead.com/npc=108600/sister-of-the-moon-saved)

Behavior: Sisters of the Moon are not rescuable or saveable. Can't click on them or use a buff.

Expected Behavior: [Youtube](https://www.youtube.com/watch?v=LEdQiPwv8JE)

**Comment by skeezerbean** [comment]
Sent in a fix for this
