### ISSUE TITLE
[Quest] [Legion] Grotesque Remains

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#322]
Quest ID: [42786 Grotesque Remains](https://www.wowhead.com/quest=42786/grotesque-remains)

Behavior: Quest is missing at NPC [108304](https://www.wowhead.com/npc=108304/guviena-bladesong)

Expected Behavior: Quest should be acceptable at Quest Giver.

[Video](https://www.youtube.com/watch?v=Qo47QMY1Jfw)

**Comment by skeezerbean** [comment]
The ItemID in game shows invalid and bugged, so best I can do is a chance for this quest to be given from NPCs that the item usually drops from.
Quest does not come from this NPC, it comes from an item looted.
