### ISSUE TITLE
[Quest] [Legion] Wisp in the Willows

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#323]
Quest ID: [39354](https://www.wowhead.com/quest=39354/wisp-in-the-willows)

Behaviour: Bond with the [110572 Wisp](https://www.wowhead.com/npc=110572/wisp) is not working.

Expected Behaviour: Making a Bond with the  [110572 Wisp](https://www.wowhead.com/npc=110572/wisp) and then grow the [Budding Trees 111876](https://www.wowhead.com/npc=111876/budding-tree)

[Video](https://www.youtube.com/watch?v=RH-_txSmqHk)

**Comment by skeezerbean** [comment]
Fix already sent in
