### ISSUE TITLE
[NPC] [Item] [Legion] Warden's Signet

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#324]
NPC ID: [Lelyn Swiftshadow 94366](https://www.wowhead.com/npc=94366/lelyn-swiftshadow)
Item ID: [Warden's Signet 127860](https://www.wowhead.com/item=127860/wardens-signet)
Quest ID: [The Warden's Signet 38711](https://www.wowhead.com/quest=38711/the-wardens-signet)

Current Behaviour: [NPC Lelyn Swiftshadow 94366](https://www.wowhead.com/npc=94366/lelyn-swiftshadow) is not dropping needed [Item Warden's Signet 127860](https://www.wowhead.com/item=127860/wardens-signet) to start the [Quest The Warden's Signet 38711](https://www.wowhead.com/quest=38711/the-wardens-signet) 

Expected Behaviour: NPC needs to drop that Item at the first time you kill her.

**Comment by skeezerbean** [comment]
Another bugged item, set this to have a chance to give quest on NPC death
