### ISSUE TITLE
[Quest] [Legion] Moozy's Sojourn

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#325]
Quest ID: [Moozy's Sojourn 39323](https://www.wowhead.com/quest=39323/moozys-sojourn)
NPC ID: Start : [Rordan Waterwise](https://www.wowhead.com/npc=96083/rordan-waterwise) End : [Moozy Waterwise 95130](https://www.wowhead.com/npc=95130/moozy-waterwise)

Current Behaviour: Quest is missing and not acceptable.

Expected Behaviour: After accepting Quest [Spray and Prey 39277](https://www.wowhead.com/quest=39277/spray-and-prey) the Quest [Moozy's Sojourn 39323](https://www.wowhead.com/quest=39323/moozys-sojourn) should be available

**Comment by skeezerbean** [comment]
Quest should be available after 3 quests completed - see for details - https://wowpedia.fandom.com/wiki/Moozy%27s_Sojourn
Sending in fix for multiple quest order issues with a few related quests
