### ISSUE TITLE
[Quest] [NPC] [Legion] Invading Spelunkers

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#326]
Quest ID: [Invading Spelunkers 39489](https://www.wowhead.com/quest=39489/invading-spelunkers)
[Balance of Elements 39488](https://www.wowhead.com/quest=39488/balance-of-elements)

NPC ID: [Violent Crageater 95916](https://www.wowhead.com/npc=95916/violent-crageater)

Current Behaviour: [Violent Crageater 95916](https://www.wowhead.com/npc=95916/violent-crageater) killing them doesn't give Kill Credits... and Quest [Invading Spelunkers 39489](https://www.wowhead.com/quest=39489/invading-spelunkers) should be available after accepting Quest [Balance of Elements 39488](https://www.wowhead.com/quest=39488/balance-of-elements) but it is only acceptable after completing [Balance of Elements 39488](https://www.wowhead.com/quest=39488/balance-of-elements) .

Expected Behaviour: NPC  [Violent Crageater 95916](https://www.wowhead.com/npc=95916/violent-crageater) should give Kill Credits and Quest [Invading Spelunkers 39489](https://www.wowhead.com/quest=39489/invading-spelunkers) should be available after accepting Quest [Balance of Elements 39488](https://www.wowhead.com/quest=39488/balance-of-elements) ( not completing!!!! )

Video: [Youtube](https://www.youtube.com/watch?v=XxyVzAzIqZ0)

**Comment by skeezerbean** [comment]
Fix sent in for kill credit. Quest order already addressed in an earlier fix
