### ISSUE TITLE
[Quest] [Legion] Wrathshard

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#327]
Quest ID: [Wrathshard 39134](https://www.wowhead.com/quest=39134/wrathshard)

Current Behaviour: Quest is missing at Start NPC [Warbrave Nara](https://www.wowhead.com/npc=94561/warbrave-nava)

Expected Behaviour: Quest should be available since the beginning

**Comment by skeezerbean** [comment]
Fix sent in, quest was requiring prerequisite of a Legion quest that never made it out of alpha.
