### ISSUE TITLE
[Quest] [Item] [Legion] To See the Past

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#329]
Quest ID: [To See the Past 40520](https://www.wowhead.com/quest=40520/to-see-the-past)
NPC ID: [Darkshard Crystal 100445](https://www.wowhead.com/npc=100445/darkshard-crystal)
Item ID: [Darkshard Crystal 132246](https://www.wowhead.com/item=132246/darkshard-crystal)

Current Behaviour: Quest Item [Darkshard Crystal 132246](https://www.wowhead.com/item=132246/darkshard-crystal) is not dropping at the first time killing the NPC [Darkshard Crystal 100445](https://www.wowhead.com/npc=100445/darkshard-crystal)

Expected Behaviour: Quest Item [Darkshard Crystal 132246](https://www.wowhead.com/item=132246/darkshard-crystal) should drop at the first time killing the NPC [Darkshard Crystal 100445](https://www.wowhead.com/npc=100445/darkshard-crystal)

Videos: [Youtube](https://www.youtube.com/watch?v=jt5tCxm3jjo&t=71s)

**Comment by skeezerbean** [comment]
Sent in a fix
