### ISSUE TITLE
problems with IMPORTANT missions

### ISSUE THREAD

**Issue by saantres** [holydeew/WoWHellgarve-Legion#33]
I have problems with these 2 missions of great importance to advance the content of the game..
they are both to release power and to release flight system...

the first is https://es.wowhead.com/quest=48799/combustible-de-un-mundo-condenado 
which is important in the quest chain, the problem is the following: those items are farmed by killing the rare bugs in all argus, the error said items do not fall, I have been trying for more than 12 hours and nothing....

the second is: https://es.wowhead.com/quest=48461/donde-menos-se-lo-esperan
When completing the chain of individual missions automatically, when you reach this point, the lower invasion points are released, which is not seen on the entire map or the missions as such.

please please fix the main bugs in the game both the flight quest chains and the class quest bugs as it affects the gameplay of every 1 of us as players...
Thank you very much, I look forward to answers....
and remember
THEY ARE NOT PREPARED

**Comment by skeezerbean** [comment]
https://www.wowhead.com/quest=48799/fuel-of-a-doomed-world

This works fine, as intended. The NPCs that spawn are rare elites that are not always spawned. The drop rate is 100%, and dropped while I had this quest active
The chests also drop, but more like 10-20%

For this - https://www.wowhead.com/quest=48461/where-they-least-expect-it
This I have no idea and will have to pass to someone else to look at. Until then, you'll have to run around and find them I assume 😸
