### ISSUE TITLE
[Quest] [Legion] Titanic Showdown

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#330]
Quest ID: [Titanic Showdown 39578](https://www.wowhead.com/quest=39578/titanic-showdown)
NPC ID: [Vision of Deathwing 97056](https://www.wowhead.com/npc=97056/vision-of-deathwing)

Current Behaviour: Quest is working as usuall but after clicking [96318 Vision of Deathwing](https://www.wowhead.com/npc=96318/vision-of-deathwing) NPC  [Vision of Deathwing 97056](https://www.wowhead.com/npc=97056/vision-of-deathwing) is not spawning instantly.

Expected Behaviour: After clicking [96318 Vision of Deathwing](https://www.wowhead.com/npc=96318/vision-of-deathwing) NPC [Vision of Deathwing 97056](https://www.wowhead.com/npc=97056/vision-of-deathwing) should spawn instantly and not after 10minutes. 

Video: [Youtube](https://www.youtube.com/watch?v=mQ_TIwPAhaY)

**Comment by skeezerbean** [comment]
Sent in a fix.
All NPCs were static spawns, so if you didn't see deathwing it was because he was killed and despawned. This should respond much better now, and summon only if a player nearby is at this stage of the quest and isn't spawned already
