### ISSUE TITLE
[Quest] [Legion] Critter Scatter Shot

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#331]
Quest ID: [39670 Critter Scatter Shot](https://www.wowhead.com/quest=39670/critter-scatter-shot)
NPC ID: [96513 Razik Gazbolt](https://www.wowhead.com/npc=96513/razik-gazbolt)

Current Behaviour: Quest giver [96513 Razik Gazbolt](https://www.wowhead.com/npc=96513/razik-gazbolt) does not have this quest available [39670 Critter Scatter Shot](https://www.wowhead.com/quest=39670/critter-scatter-shot)

Expected Behaviour:  Quest giver [96513 Razik Gazbolt](https://www.wowhead.com/npc=96513/razik-gazbolt) should have this quest available without doing any other quests [39670 Critter Scatter Shot](https://www.wowhead.com/quest=39670/critter-scatter-shot)

**Comment by skeezerbean** [comment]
Sent in a fix
