### ISSUE TITLE
[Quest] [Legion] The Skyhorn Tribe

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#332]
Quest ID: [38913 The Skyhorn Tribe](https://www.wowhead.com/quest=38913/the-skyhorn-tribe)
NPC ID: [Lasan Skyhorn](https://www.wowhead.com/npc=93841/lasan-skyhorn)

Current Behaviour: Quest [38913 The Skyhorn Tribe](https://www.wowhead.com/quest=38913/the-skyhorn-tribe) is not turnable at Quest End NPC [Lasan Skyhorn](https://www.wowhead.com/npc=93841/lasan-skyhorn)

Expected Behaviour: Quest [38913 The Skyhorn Tribe](https://www.wowhead.com/quest=38913/the-skyhorn-tribe) should be turnable at Quest End NPC [Lasan Skyhorn](https://www.wowhead.com/npc=93841/lasan-skyhorn) without doing any other steps

**Comment by skeezerbean** [comment]
Sent in a fix
