### ISSUE TITLE
[Quest] [Legion] Nursing the Wounds

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#333]
Quest ID [Nursing the Wounds 39318](https://www.wowhead.com/quest=39318/nursing-the-wounds)

NPC ID [Lasan Skyhorn 93841](https://www.wowhead.com/npc=93841/lasan-skyhorn)

Current Behaviour: Quest [Nursing the Wounds 39318](https://www.wowhead.com/quest=39318/nursing-the-wounds) is missing at Quest NPC [Lasan Skyhorn 93841](https://www.wowhead.com/npc=93841/lasan-skyhorn)

Expected Behaviour: After turning in Quest [The Skyhorn Tribe 38913](https://www.wowhead.com/quest=38913/the-skyhorn-tribe) Quest [Nursing the Wounds 39318](https://www.wowhead.com/quest=39318/nursing-the-wounds) should be available at NPC [Lasan Skyhorn 93841](https://www.wowhead.com/npc=93841/lasan-skyhorn)

**Comment by skeezerbean** [comment]
sent in a fix
