### ISSUE TITLE
[Quest] [Legion] I'm not Lion!

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#335]
Quest ID: [I'm not Lion! 39867](https://www.wowhead.com/quest=39867/im-not-lion)
NPC ID: [Ellias 95438](https://www.wowhead.com/npc=95438/ellias) , [Rashar 97454](https://www.wowhead.com/npc=97454/rashar)
Item ID: [Rashar's Right Eye 128933](https://www.wowhead.com/item=128933/rashars-right-eye)

Current Behaviour: Quest Giver [Ellias 95438](https://www.wowhead.com/npc=95438/ellias) does not have this Quest [I'm not Lion! 39867](https://www.wowhead.com/quest=39867/im-not-lion) available.

Expected Behaviour: Quest Giver [Ellias 95438](https://www.wowhead.com/npc=95438/ellias) should have this Quest [I'm not Lion! 39867](https://www.wowhead.com/quest=39867/im-not-lion) available. After accepting the Quest you go and search for NPC [Rashar 97454](https://www.wowhead.com/npc=97454/rashar) and kill him. At the first time killing him, he should drop a Quest Item called  [Rashar's Right Eye 128933](https://www.wowhead.com/item=128933/rashars-right-eye). After getting this Item you should be available to turn in this Quest at [Ellias 95438](https://www.wowhead.com/npc=95438/ellias) .

Video: [Youtube](https://www.youtube.com/watch?v=1fOcfJwYSMU)

**Comment by skeezerbean** [comment]
This quest is offered and works, but you must have cooking skill learned (even just level 1) for it to show available.
