### ISSUE TITLE
[Quest] [Legion] Justice Rains from Above

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#336]
Quest ID [Justice Rains from Above 40594](https://www.wowhead.com/quest=40594/justice-rains-from-above)

NPC IDs : [100712 War Eagle](https://www.wowhead.com/npc=100712/war-eagle), [Lasan Skyhorn 97407](https://www.wowhead.com/npc=97407/lasan-skyhorn)

Current Behaviour: Quest [Justice Rains from Above 40594](https://www.wowhead.com/quest=40594/justice-rains-from-above) is missing at Quest Giver  [Lasan Skyhorn 97407](https://www.wowhead.com/npc=97407/lasan-skyhorn) 

Expected Behaviour: Quest should be available at Quest Giver after completing and turning in Quest [Evacuate Snowmane 42088](https://www.wowhead.com/quest=42088/evacuate-snowmane)

Video how this Quest is suposed to work [Youtube](https://www.youtube.com/watch?v=_fH8IckbaPQ)

**Comment by skeezerbean** [comment]
Sent in a fix, as well as credit when healing friendly NPCs from the war eagle
