### ISSUE TITLE
[Quest] {Legion] [Alliance] [Stormheim] Stormforged Grapple Launcher

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#337]
Quest ID [Stormforged Grapple Launcher 39775](https://www.wowhead.com/quest=39775/stormforged-grapple-launcher)

NPC ID: [Stormforged Grapple Launcher 107840](https://www.wowhead.com/npc=107840/stormforged-grapple-launcher)

Item ID: [Stormforged Grapple Launcher 138111](https://www.wowhead.com/item=138111/stormforged-grapple-launcher)

Current Behaviour: NPC [Stormforged Grapple Launcher 107840](https://www.wowhead.com/npc=107840/stormforged-grapple-launcher) is missing next to the stone where it should be. Can't complete Quest [Stormforged Grapple Launcher 39775](https://www.wowhead.com/quest=39775/stormforged-grapple-launcher)

Expected Behaviour: NPC [Stormforged Grapple Launcher 107840](https://www.wowhead.com/npc=107840/stormforged-grapple-launcher) with Quest [Stormforged Grapple Launcher 39775](https://www.wowhead.com/quest=39775/stormforged-grapple-launcher) should be at this Cords 33.7 x 45.8. 

Video: [Youtube](https://www.youtube.com/watch?v=fVqqPfhj0JQ)

**Comment by skeezerbean** [comment]
Sent in a fix that removed a duplicate, and added NPC to missing locations. Also forced grapple points to only work if this quest was rewarded across the zone, as well as update a better visual when using the grapple points.
