### ISSUE TITLE
[Quest] [Legion] Murlocs: The Next Generation

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#338]
Quest ID: [Murlocs: The Next Generation 40102](https://www.wowhead.com/quest=40102/murlocs-the-next-generation)
Quest Start and End ID: [King Mrgl Mrgl](https://www.wowhead.com/npc=98067/king-mrgl-mrgl)
NPC ID: [Murky's Egg 89630](https://www.wowhead.com/npc=89630/murkys-egg-opened)

Current Behaviour: [King Mrgl Mrgl](https://www.wowhead.com/npc=98067/king-mrgl-mrgl) does not have this Quest available.

Expected Behaviour: [King Mrgl Mrgl](https://www.wowhead.com/npc=98067/king-mrgl-mrgl) should have Quest [Murlocs: The Next Generation 40102](https://www.wowhead.com/quest=40102/murlocs-the-next-generation) available

Video: [Youtube](https://www.youtube.com/watch?v=Hzq8RRA1AeU)

**Comment by skeezerbean** [comment]
This is a cooking quest. It is available if you have the skill.
