### ISSUE TITLE
[Quest] [Legion] [Alliance] [Horde] Built to Scale

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#339]
**Quest ID:**  For Alliance !! [Built to Scale 38337](https://www.wowhead.com/quest=38337/built-to-scale) For Horde !! [Built to Scale 38616](https://www.wowhead.com/quest=38616/built-to-scale)
**Quest Start:** For Alliance !! [Storm Drake Scale 122610](https://www.wowhead.com/item=122610/storm-drake-scale) For Horde [Storm Drake Scale 124037](https://www.wowhead.com/item=124037/storm-drake-scale)
**Quest End:** For Alliance !! [Commander Lorna Crowley 91222](https://www.wowhead.com/npc=91222/commander-lorna-crowley) For Horde !! [Dread-Rider Cullen 92561](https://www.wowhead.com/npc=92561/dread-rider-cullen)
**NPC ID:** [Stormwing Drake 91202](https://www.wowhead.com/npc=91202/stormwing-drake)
**Item ID:** [Storm Drake Scale 122609](https://www.wowhead.com/item=122609/storm-drake-scale)

**ONLY FOR ALLIANCE NOW!!!!**

Current Behaviour:  Killing NPC [Stormwing Drake 91202](https://www.wowhead.com/npc=91202/stormwing-drake) and looting Item [Storm Drake Scale 122610](https://www.wowhead.com/item=122610/storm-drake-scale) starts the Quest as usual but killing more NPCS [Stormwing Drake 91202](https://www.wowhead.com/npc=91202/stormwing-drake) drop this Item [Storm Drake Scale 124037](https://www.wowhead.com/item=124037/storm-drake-scale) for Horde  everytime. Then looting this Item  [Storm Drake Scale 122609](https://www.wowhead.com/item=122609/storm-drake-scale) gives you Quest Credit that Quest is complete even when you only have 1/50 or 11/50. Item [Storm Drake Scale 122609](https://www.wowhead.com/item=122609/storm-drake-scale)  has low drop rate which is not normal like in retail.

Expected Behaviour: When killing NPC [Stormwing Drake 91202](https://www.wowhead.com/npc=91202/stormwing-drake) as Alliance it should only drop this Quest Start Item [Storm Drake Scale 122610](https://www.wowhead.com/item=122610/storm-drake-scale) only one time or when you have this Quest already in your Quest Log it should not drop the Quest Start Item [Storm Drake Scale 124037](https://www.wowhead.com/item=124037/storm-drake-scale) for Horde!!! When Looting [Storm Drake Scale 122609](https://www.wowhead.com/item=122609/storm-drake-scale) credit should show correct and not quest completed when you have not farmed 50 pieces of it. Last not but least Item  [Storm Drake Scale 122609](https://www.wowhead.com/item=122609/storm-drake-scale) should have a higher drop rate.

Video: [Alliance](https://www.youtube.com/watch?v=p6h_U7d4E2M) [Horde](https://www.youtube.com/watch?v=Ys_t0gTyxWQ)

**Comment by skeezerbean** [comment]
I removed item drops to start the quest. Instead, killing one of the dragons will give you the quest based on faction. Works fine now, sending in the fix
