### ISSUE TITLE
flying to bloodmyst isle.

### ISSUE THREAD

**Issue by karlbeh** [holydeew/WoWHellgarve-Legion#34]
my character is caught in a loop. when i log in my character he takes off from the flight path at teldrassil to bloodmyst isle. after the phase from the classic-teldrassil zone to the burning crusade-bloodmyst isle zone my character is swimming instead of flying and then gets disconnected from the server.

**Comment by skeezerbean** [comment]
I've learned all flight paths on Azuremyst, Bloodmyst and in Teldrassil. I have no options to fly from there to the TBC zones, only a boat ride. What NPCs are you talking to that give this option, and what destination are you selecting?

**Comment by skeezerbean** [comment]
This should be fixed as "all flight paths" was turned off server-side, and what was causing the issue. This flight path is not something that exists naturally and why it was crashing on zone changes.
