### ISSUE TITLE
[Quest] [Legion] Rigging the Wager

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#340]
Quest ID: [Rigging the Wager 39787 ](https://www.wowhead.com/quest=39787/rigging-the-wager)
Object ID: [Spitefeather's Rock 244457](https://www.wowhead.com/object=244457/spitefeathers-rock)
NPC ID: [Spitefeather 97124](https://www.wowhead.com/npc=97124/spitefeather)
Item ID: [Spitefeather's Beak 138022](https://www.wowhead.com/item=138022/spitefeathers-beak)

Current Behaviour: Clicking on Object  [Spitefeather's Rock 244457](https://www.wowhead.com/object=244457/spitefeathers-rock) doesn't spawns [Spitefeather 97124](https://www.wowhead.com/npc=97124/spitefeather)

Expected Behaviour:  Clicking on Object  [Spitefeather's Rock 244457](https://www.wowhead.com/object=244457/spitefeathers-rock) should spawn [Spitefeather 97124](https://www.wowhead.com/npc=97124/spitefeather) and killing [Spitefeather 97124](https://www.wowhead.com/npc=97124/spitefeather)  should drop this Item [Spitefeather's Beak 138022](https://www.wowhead.com/item=138022/spitefeathers-beak) with 100% drop rate

Video: [Youtube](https://www.youtube.com/watch?v=Q5l4w_vf9eE)

**Comment by skeezerbean** [comment]
Sent in a fix, but drop is not 100%
