### ISSUE TITLE
[Quest] [Legion] A Heavy Burden

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#341]
Quest ID: [A Heavy Burden 40078](https://www.wowhead.com/quest=40078/a-heavy-burden)
Quest Start / End ID: [Havi 92539](https://www.wowhead.com/npc=92539/havi)

Current Behaviour: Quest [A Heavy Burden 40078](https://www.wowhead.com/quest=40078/a-heavy-burden) is missing at Quest NPC [Havi 92539](https://www.wowhead.com/npc=92539/havi)

Expected Behaviour: Quest [A Heavy Burden 40078](https://www.wowhead.com/quest=40078/a-heavy-burden) should be available at Quest Giver [Havi 92539](https://www.wowhead.com/npc=92539/havi) after completing quest [Paid in Lifeblood 39855](https://www.wowhead.com/quest=39855/paid-in-lifeblood)

**Comment by skeezerbean** [comment]
This quest is offered, but a cooking recipe quest that requires cooking to see. Cleaned up some phasing/scripting for the quest itself.
