### ISSUE TITLE
[Quest] [Legion] Put It All on Red

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#342]
Quest ID: [Put It All on Red 42483](https://www.wowhead.com/quest=42483/put-it-all-on-red)
NPC: [Steelscale 107917](https://www.wowhead.com/npc=107917/steelscale)
Item: [Steelscale's Fin 138024](https://www.wowhead.com/item=138024/steelscales-fin)

Current Behaviour: Killing NPC [Steelscale 107917](https://www.wowhead.com/npc=107917/steelscale) does not drop Item [Steelscale's Fin 138024](https://www.wowhead.com/item=138024/steelscales-fin) at the first time

Expected Behaviour: Killing NPC [Steelscale 107917](https://www.wowhead.com/npc=107917/steelscale) should drop Item [Steelscale's Fin 138024](https://www.wowhead.com/item=138024/steelscales-fin) at the first time.

Video: [Youtube](https://www.youtube.com/watch?v=TCM41V9Vlis)

**Comment by skeezerbean** [comment]
The item is already set to 100% drop. I killed 6 times, got it to drop 6 times. Wowhead shows drop rate 93%
