### ISSUE TITLE
[Quest] [Legion] Nobundo's Last Stand

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#344]
Quest ID: [Nobundo's Last Stand 43705](https://www.wowhead.com/quest=43705/nobundos-last-stand)
Quest Start / End: [Farseer Nobundo 110695](https://www.wowhead.com/npc=110695/farseer-nobundo)
NPC ID: [Farseer Nobundo 110695](https://www.wowhead.com/npc=110695/farseer-nobundo)

Current Behaviour: Can't talk with [Farseer Nobundo 110695](https://www.wowhead.com/npc=110695/farseer-nobundo) to start the Assault

Expected Behaviour: Talking with NPC [Farseer Nobundo 110695](https://www.wowhead.com/npc=110695/farseer-nobundo) should start the Assault

Video: [Youtube](https://www.youtube.com/watch?v=lsE3SCY18uo)

**Comment by skeezerbean** [comment]
Scripted the event, sent in the fix
