### ISSUE TITLE
[Quest] [Item] [Legion] [Dungeon NM&HC] Maw of Souls: Ymiron's Broken Blade 

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#345]
Quest ID: [Maw of Souls: Ymiron's Broken Blade 43604](https://www.wowhead.com/quest=43604/maw-of-souls-ymirons-broken-blade)
Quest Start: [Ymiron's Broken Blade 139619](https://www.wowhead.com/item=139619/ymirons-broken-blade)
Quest End: [Odin 96469](https://www.wowhead.com/npc=96469/odyn)
Item ID: [Ymiron's Broken Blade 139619](https://www.wowhead.com/item=139619/ymirons-broken-blade)
NPC: [Ymiron, the Fallen King 96756](https://www.wowhead.com/npc=96756/ymiron-the-fallen-king)

Current Behaviour: After accepting Quest [Maw of Souls: Message to Helya 43586](https://www.wowhead.com/quest=43586/maw-of-souls-message-to-helya) killing [Ymiron, the Fallen King 96756](https://www.wowhead.com/npc=96756/ymiron-the-fallen-king) is not dropping [Ymiron's Broken Blade 139619](https://www.wowhead.com/item=139619/ymirons-broken-blade) to start Quest [Maw of Souls: Ymiron's Broken Blade 43604](https://www.wowhead.com/quest=43604/maw-of-souls-ymirons-broken-blade)

Expected Behaviour: After accepting Quest [Maw of Souls: Message to Helya 43586](https://www.wowhead.com/quest=43586/maw-of-souls-message-to-helya) killing [Ymiron, the Fallen King 96756](https://www.wowhead.com/npc=96756/ymiron-the-fallen-king) should drop [Ymiron's Broken Blade 139619](https://www.wowhead.com/item=139619/ymirons-broken-blade) to start Quest [Maw of Souls: Ymiron's Broken Blade 43604](https://www.wowhead.com/quest=43604/maw-of-souls-ymirons-broken-blade)

Video: Not existend

Edit: 

Talking with [Odyn 96469](https://www.wowhead.com/npc=96469/odyn) is not completing Quest [Maw of Souls: Ymiron's Broken Blade 43604](https://www.wowhead.com/quest=43604/maw-of-souls-ymirons-broken-blade) but talking with [Odyn 96469](https://www.wowhead.com/npc=96469/odyn) should complete the quest.

**Comment by skeezerbean** [comment]
Sending in a fix for this, both for looting the item as long as Helya's quest has any status at all, and being able to get credit from Odyn.
