### ISSUE TITLE
Quest: [Socket to me]

### ISSUE THREAD

**Issue by domdiego44** [holydeew/WoWHellgarve-Legion#348]
Quest: https://www.wowhead.com/quest=40558/socket-to-me

Only tried to get the first object: https://www.wowhead.com/item=132842/crystal-shardject (Crystal Shard), wich is a 100 % drop according to wowhead. Killed https://www.wowhead.com/npc=101630/amberstone-earthrender 3x, and no drop.

Edit: Crystal Core, also 100% drop, doesn't work also. https://www.wowhead.com/npc=108950/crimson-geode
Crystal Scale: https://www.wowhead.com/item=132840/crystal-scale - also don't work

**Comment by skeezerbean** [comment]
Sent in a fix. The Crystal Plume was the only one working correctly. The rest were inconsistent or not dropping at all.
