### ISSUE TITLE
Quest: 44920 don't work as intended.

### ISSUE THREAD

**Issue by AlveronAlsv** [holydeew/WoWHellgarve-Legion#35]
https://www.wowhead.com/quest=44920/order-of-incantations
When it comes to clicking on the stones in a certain order, the stones cannot be clicked.

**Comment by skeezerbean** [comment]
I'm sending a fix for this, as well as the followup quest was unscripted as well. Once this is applied then the nearby NPCs should respond as intended, as well as the gems/barrier, and the followup quest scripting
