### ISSUE TITLE
[Bug] [Bank of Reagent] Clean Up Reagent Bank not correctly working.

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#350]
**Bug report :** Stack-buying don't work on 1 specific vendor

**Date :** July 13, 2023

**Bug description :**
I just see that the Clean-up Button don't work correctly in the Reagent Bank. Yes when you clicking the Clean-up button of the Reagent bank, this, clean the reagents by put it IN the NORMAL bank, and that's a problem.

**Expected Result :**
When clicking the Clean-up Button on the Reagent bank, it must just clean the Reagent IN the Reagent Bank.

**Bug Impact :**
When you have 313 543 546 543M reagent and you don't want to have in the normal bank, clicking the Clean-up Button and see this... it's awfull

**Vidéo :** https://youtu.be/Nu6SOXWEV2I

**Comment by skeezerbean** [comment]
Sending in a fix for this
