### ISSUE TITLE
Quest: The Seat of the Triumvirate: Armor of the Triumvirate

### ISSUE THREAD

**Issue by domdiego44** [holydeew/WoWHellgarve-Legion#351]
https://www.wowhead.com/quest=48231/the-seat-of-the-triumvirate-armor-of-the-triumvirate    --- quest bugged with any alt that doesn't have a stealth possibility (rogue, mage, or any elf race). In the zone to loot the chest of the armor, i'm always reported as being "in combat", and i'm not. Being a DK of not elf race, i can't stealth or shadowmeld, so i can't loot or use potion or device.
BTW: https://www.wowhead.com/item=151912/shroud-of-arcane-echoes doesn't work inside that instance.

**Comment by skeezerbean** [comment]
Sending in a fix to allow the chest to be looted regardless of being in combat
