### ISSUE TITLE
Quest - Unusual Behavior...Even for Gnolls

### ISSUE THREAD

**Issue by Aizen26** [holydeew/WoWHellgarve-Legion#352]
Quest - Unusual Behavior...Even for Gnolls
Location: Western Plaguelands
NPC/Mob: Moldfang
Issue: The Quest cannot be completed because the NPC Moldfang didn't registered as killed in the script. Instead i got this message pop-up on the screen.

![WoWScrnShot_081623_200251](https://github.com/holydeew/WoWHellgarve-Legion/assets/137589309/a0ac2678-b8f7-4512-a0f7-f6691b6bdfc6)

https://www.wowhead.com/quest=27152/unusual-behavior-even-for-gnolls

**Comment by skeezerbean** [comment]
Sent in a fix for this
