### ISSUE TITLE
Illidan Stormrage <The Betrayer>

### ISSUE THREAD

**Issue by KORDREVIX** [holydeew/WoWHellgarve-Legion#353]
The boss is coming of tbc , he provided of the raid called Black Temple.

The problem with the boss is taht when he dies you ca looted it soo you can have the full tier o the Azzinoth's Warglaives that is an item for trasmog and an item that a lot of player want have. 
Not only the item of Azzinoth's Warglaives there are achievements that you cant get for example: The archievement of kill illidan 

https://youtu.be/jceE6Ihj460

There is a video checking that when he dies you cant recolect the things

**Comment by skeezerbean** [comment]
I really have no idea what I just read. What is the actual issue? I've killed this NPC, items dropped. I haven't looked at the loot lists so I don't know what all is there, but I need details on an actual issue and I am not sure what this post is trying to say. Closing, edit and re-open if needed.
