### ISSUE TITLE
[QUEST]The Second Trial of Ursol

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#354]
**Bug report :** 7/SEPT/2023

**Quest : ** https://www.wowhead.com/quest=41791/the-second-trial-of-ursol

**Bug description :** The quest goes well, but the enemy NPC= 104937 are in "boss" level. They are in level 110 instead of your current level. For example: level 100. 

**Expected Result :** NPC must be at the same level than the player's character.

**Screenshots :**
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/75407049/f3de49d1-8ee6-48f2-9e08-041dea3cf0dc)
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/75407049/07ab2c96-5ce3-4111-9d60-162c8bc0cf96)
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/75407049/87dce9b5-9b21-4385-8d91-e2424afb5eb7)

**Comment by skeezerbean** [comment]
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/d45fa49b-40d3-4438-b7bb-b00ac1df1e24)

NPC already has proper scaling data set, so this is a source bug from summoned NPCs defaulting to max level when they are summoned through scripts (works fine when player summons via spell). Not something that can be fixed at the moment.

**Comment by asd1488** [comment]
> ![image](https://user-images.githubusercontent.com/19826665/266486144-d45fa49b-40d3-4438-b7bb-b00ac1df1e24.png)
> 
> NPC already has proper scaling data set, so this is a source bug from summoned NPCs defaulting to max level when they are summoned through scripts (works fine when player summons via spell). Not something that can be fixed at the moment.

So, it's source?

**Comment by skeezerbean** [comment]
Ok, so I rescripted this and bypassed the spell that's used to trigger the spawning, and spawned a different way so that they spawn and honor scaling data. I made sure the NPCs still trigger credit ok to the correct player, that Ursol responds correctly to this, and also that they attack the correct player on summon by default. Sending in the fix...
