### ISSUE TITLE
[QUEST] "the-nexus-vault"

### ISSUE THREAD

**Issue by ArchHellgarve** [holydeew/WoWHellgarve-Legion#360]
ID: 41631

In the part where we have to go to the library (llibrarium), Azuregos does not follow us along the path, which makes it impossible to complete the mission, and artifact (disci priest)

**Comment by skeezerbean** [comment]
Once entering the scenario and killing anything to get him to start, he should head that direction. At what point is it breaking?

**Comment by ArchHellgarve** [comment]
In the final section of the route to the library (llibrarium), Azuregos does not follow the player and remains stationary at the last intersection to approach the llibrarium.

But, when I did the mission for the wizard, Azuregos did accompany him correctly.

**Comment by skeezerbean** [comment]
This is now fixed for Priest, fix was sent in but not sure when it will get applied.
