### ISSUE TITLE
Paladin Protection Legendary Quest - Shrine of the Truthguard

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#362]
This is the first legendary weapon I'm completing on this paladin and the starting fight involving the dragon and rider is way too hard. The spear that drops mostly ends up under the ground. The damage the two outputs easily surpasses my ability to heal (in Protection Spec). Those two things combined and I was unable to complete the fight after multiple attempts. I actually ran myself dry on gold in repair costs just attempting it.

**Comment by skeezerbean** [comment]
Sent in small adjustment to help her not to cast Shoot as much.
