### ISSUE TITLE
[Quest Artifact Druid Balance] "Following the Curse"

### ISSUE THREAD

**Issue by ArchHellgarve** [holydeew/WoWHellgarve-Legion#363]
Quest ID: 40834

Issue: It starts normally, but having to enter the Karazhan area, the npc does not move, does not accompany, and the mission cannot be carried out.

**Comment by skeezerbean** [comment]
When you enter, pause near him for a moment and he should respond. If you did this, and he started to follow, did you die later and he stopped?

**Comment by ArchHellgarve** [comment]
Hello. He only accompanies you in the Duskwood, he does not move from there no matter how much you wait, enter again, resume the mission, etc.

I never previously died on the mission

**Comment by skeezerbean** [comment]
I'm having no issues with this, tested on Hellgarves server. I cannot reproduce this. He follows into Deadwind pass fine, all the way to his camp. The followup quests have you enter Karazhan, and as soon as I enter and stop for a moment next to him, he follows me there also.
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/d8a51590-6b87-4b90-a2a3-1cf65cc76bec)
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/f0952ef1-b2eb-4e40-90a1-e39549da0cdc)
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/3d89b59a-119d-4dd4-a0a2-48263ad8887e)
