### ISSUE TITLE
[QUEST] Storm, Earth, and Fire

### ISSUE THREAD

**Issue by ArchHellgarve** [holydeew/WoWHellgarve-Legion#364]
ID: 41731 https://www.wowhead.com/quest=41731/storm-earth-and-fire

class: monk

zone: Pandaria

Although the mission takes what you shoot down spikes, it does not add to the final counter of the quest and cannot be delivered.

**Comment by skeezerbean** [comment]
I can't find an issue

![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/84021561-163d-47b5-9d20-8a19476cb45a)

![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/499836c6-ebb6-4edf-a2ab-7d0188fa66ec)
