### ISSUE TITLE
Server Documentation

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#368]
I asked on Discord and they suggested I make my suggestions here. There is a large lack of documentation/server settings. I just spent 10 minutes flying around trying to figure out how to reset my talents to try something different. Come to find out you can just change them on the fly in a city. 100% not a complaint, I love this system so much. But I would like to have just been able to read that was a thing here and not spend the 10 minutes prior wasted. It honestly never occurred to me to try it because it just has never been a thing. 

There are a few other things I've come across that are comfort features, but without any documentation, I had no idea about it. 

Thanks for the server!

**Comment by skeezerbean** [comment]
It has been this way for a while in retail. It isn't something specific to this server.
