### ISSUE TITLE
[Dungeon] Scarlet Halls

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#37]
A bug that removes the ability from players to kill creatures.

How to reproduce:

After killing Armsmaster Harlan and getting hit by his bladestorm the Player is unable to kill creatures after that.
The Creatures will continuesly reset themself.

Also Armsmaster Harlan getting stuck in an endless loop of Blades of Light never ending, continuesly spinning.

Links:
NPC: https://wowhead.com/npc=58632/
Spell: https://wowhead.com/spell=111216/

**Comment by skeezerbean** [comment]
Sending in a fix for this
