### ISSUE TITLE
[Spell] Zen Pilgrimage

### ISSUE THREAD

**Issue by Xiirel** [holydeew/WoWHellgarve-Legion#376]
Issue : The skill [Zen Pilgrimage] teleports me to the monks' domain but when I use it again, it doesn't take me back to where I was before but it puts me back in the domain
How it should normally work : Use Zen Pilgrimage again to return back to near your departure point.

Class: monk

https://www.wowhead.com/spell=126892/zen-pilgrimage

**Comment by skeezerbean** [comment]
Sending in a fix for this to be applied soon
