### ISSUE TITLE
Traveler's Tundra Mammoth - NPC's are not neutral

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#377]
I bought 2 of these so far and the vendors are the wrong faction making them useless. They don't attack me luckily but I cannot interact with them in any way.

**Comment by skeezerbean** [comment]
I cannot reproduce this. If it's still an issue then I need more details. It uploads 2 mounts. One for Alliance, the other for Horde. Depending on your faction it summons the one you need, and both have green vendor NPCs I can interact with.
