### ISSUE TITLE
Respawn of Quest item(s)

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#378]
The respawn on quest items (collectibles) is rather long. In a group of 5 to complete one quest that involves one or more items, it can take an absurd amount of time to get through them all since each player/character is stuck standing around waiting for the object to respawn. Can this be shortened to maybe a few seconds over the 1/1.5 minutes it is set to now?

**Comment by jdbhkf** [comment]
Update: I tested the quest collection rate using a quest in Azsuna - The Tidestone: Shattered. It involves collecting 5 Tidestone Shards. Each shard is on a 3-minute timer, there is a % that you get nothing when you click on them or there is a bug that causes it to not give you the item from time to time. With a team of 5 at absolute efficiency, the fastest you could complete this would be approximately 12 minutes, IF none of the collections yield no reward (very unlikely) and you count that the first round of collection is instant (they should all be spawned). The quest is in a room with not much else to do other than stand around and wait. Really not very fun at all.

**Comment by skeezerbean** [comment]
Sent in a fix to lower it a bit
