### ISSUE TITLE
[Quest] The New Blood

### ISSUE THREAD

**Issue by ArchHellgarve** [holydeew/WoWHellgarve-Legion#379]
link: https://www.wowhead.com/quest=40729/the-new-blood

Issue: Nothing happens at the beginning of the mission (the npc should open a portal but this does not happen).

**Comment by skeezerbean** [comment]
This portal is summoned through script, so accepting the quest should kick everything into gear. If it doesn't then contact a GM to .respawn NPCs (or force kill and respawn if something went really wrong lol), or wait for server restart if something whacky happened. This is in Hellgarve, not seeing an issue so can't reproduce unless I stand around and do nothing and it despawns

![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/19826665/eb478a48-0818-4ab1-8dec-218c687e587e)
