### ISSUE TITLE
Kun-Lai Summit [ Peak of Serenity ] Monk 'Class' Hall

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#38]
None of the Continue Your Training quests work at the Peark of Serenity.

You can accept the quests, you can interact with the NPCs however you can not start the Training.
Also if you choose to click on the quest it says continue but does nothing.

You can't start the Training thus you can not complete any of the quests.

This includes following quests:

Continue Your Training: Master Woo 
https://www.wowhead.com/quest=31833/continue-your-training-master-woo
Continue Your Training: Master Hsu 
https://www.wowhead.com/quest=31839/continue-your-training-master-hsu
Continue Your Training: Master Cheng 
https://www.wowhead.com/quest=31837/continue-your-training-master-cheng
Continue Your Training: Master Kistane 
https://www.wowhead.com/quest=31835/continue-your-training-master-kistane
Continue Your Training: Master Tsang 
https://www.wowhead.com/quest=31838/continue-your-training-master-tsang
Continue Your Training: Master Yoon 
https://www.wowhead.com/quest=31836/continue-your-training-master-yoon

![image](https://user-images.githubusercontent.com/26337071/180578203-1c6b7160-90f0-46e6-bd36-adec22eba750.png)

**Comment by skeezerbean** [comment]
Master Woo's quest is obsolete, was removed in 7.3.5 so I'll disable that. Checking into the others.

**Comment by skeezerbean** [comment]
Sent in an update for this entire quest chain
