### ISSUE TITLE
Idol of the Wilds [Druid Campaign]

### ISSUE THREAD

**Issue by xTWISTxDxVendetta** [holydeew/WoWHellgarve-Legion#39]
NPC Kalazzius the Guileful Does not drop the Idol of the wilds which should be a 100% drop rate it took a total of 5 Kills for him to drop it finally 

WoWhead reference: https://www.wowhead.com/npc=106042/kalazzius-the-guileful

**Comment by skeezerbean** [comment]
Fix sent to Holy
