### ISSUE TITLE
[Mage] [Quest][Aszuna] The Death of the Eldest

### ISSUE THREAD

**Issue by ArkusTele** [holydeew/WoWHellgarve-Legion#391]
Location: Aszuna
Area: Azurewing Repose
https://www.wowhead.com/quest=37853/the-death-of-the-eldest
Description: 
Slay Leyworms to obtain 6 Crackling Leyworm Cores then drop them into Senegos's pool.
QuestID: 37853
Leyworms are nowhere around to obtain the crystals to throw them into the pools later on to heal Senegos. This part of the Aszuna Campaign Zone with Khadgar

**Comment by Xiirel** [comment]
it seems to me that the worms are in the cave to the north of the area

**Comment by skeezerbean** [comment]
They exist in the place where the quest POI points to. There is more than 1 cave nearby.
