### ISSUE TITLE
Bug level 110 in quest weapon artifact warrior fury

### ISSUE THREAD

**Issue by Legionalhg** [holydeew/WoWHellgarve-Legion#394]
I'm doing the feat for the artifact weapon and this npc gives me a skull (he's level 110) and it's impossible for me to kill him, he always kills me, and I can't advance.
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/145446971/72f286bf-2910-49f9-aa24-aa82d39e2f67)
https://www.wowhead.com/es/npc=97649/helarjar-aspirante
https://www.wowhead.com/es/quest=40043/el-cazador-de-h%C3%A9roes

**Comment by skeezerbean** [comment]
Fixed
