### ISSUE TITLE
[Quest Domain Monk] stolen knowledge

### ISSUE THREAD

**Issue by Xiirel** [holydeew/WoWHellgarve-Legion#395]
the NPC doesn't allow me to loot it even though it has 100% chance

https://www.wowhead.com/quest=41039/stolen-knowledge#comments
https://www.wowhead.com/npc=102852/morjirn
https://www.wowhead.com/item=133995/storm-brew-recipe

@QuiYuelan

**Comment by skeezerbean** [comment]
Fixed
