### ISSUE TITLE
[Quest] Paladin Campaign - A New Path ?

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#398]
Delas Moonfang Spoken to has the ? near the Mission Board. Delas is actually near the Altar of Ancient Kings.

![Delas_Moonfang](https://github.com/holydeew/WoWHellgarve-Legion/assets/56544731/d98c6188-df98-459b-b054-f96b9f9a439d)

**Comment by skeezerbean** [comment]
Fix has been sent in, not sure when it will be applied
