### ISSUE TITLE
Blood Furnance Dungeon Quest

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#40]
This issue was resolved here: https://github.com/holydeew/WoWHellgarve-9.2.x/issues/718

It is the same on the Legion Realm

Quest/Spell/Item/Creature(ID) The ID is: 29539

The Current Behaviour is as following: The quest requires you to reach a certain point in the dungeon for it to be completed, but when I reach said point, its not being completed.

Expected Behaviour should be as following: Should automatically mark as completed once you reach the designated spot.

Screenshot/Video (IMGUR/YOUTUBE):

Additional Information:

**Comment by skeezerbean** [comment]
Sent a fix to Holy
