### ISSUE TITLE
[Bug] Loque'nahak cannot be tamed by BM Hunters

### ISSUE THREAD

**Issue by N7Emerald** [holydeew/WoWHellgarve-Legion#401]
When trying to tame Loque'nahak - https://www.wowhead.com/npc=32517/loquenahak game saying "Target is too high level"

**Comment by skeezerbean** [comment]
This NPC scales from 66 to 80, so if you were too low level then this is why. It may also require beastmaster spec, or possibly a specific talent. Either way it tamed fine when I tested. If still an issue then report with more details, such as your level, spec, etc.
