### ISSUE TITLE
[Artefact Choice] [Bug] Change choice, gain reputation.

### ISSUE THREAD

**Issue by Gueryghembal** [holydeew/WoWHellgarve-Legion#404]
- **Quest :** None
- **Issue :** When you change your choice of artifact, you receive, for an obscure reason, reputation for your guild.
- **How it should work normally :** it just shouldn't do that 🤷

> Indeed when we change our choice of artifact when choosing our first mage aterfact, _(and not just mage, all classes seem to be impacted)_ we receive an amount of guild reputation during the change, which is obviously not the case in normal times.
> I tested on Mage and Warrior and that the case.

Here some screen from a ticket :

Before changing (you can see on the chat that there is nothing, ofc)
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/3486f87e-d867-41ee-8e6b-eb91ce637a8a)

After changing (and you can see the little gain of reputation for your guild. 
![image](https://github.com/holydeew/WoWHellgarve-Legion/assets/105439669/5812ecc0-38c9-4965-ba3f-c3502f8db9b9)

Videos of my tries : https://youtu.be/PAlnZMonzOI
https://youtu.be/MCTFl92I6AI

**Comment by skeezerbean** [comment]
Core issue. I've set flags to disable guild xp for these and it ignores it. I'll leave it open, but not something I can fix but hopefully some day will be fixed.

**Comment by skeezerbean** [comment]
Fix sent in for this
