### ISSUE TITLE
[Quest legion herbalism] Tharillon's Fall

### ISSUE THREAD

**Issue by Xiirel** [holydeew/WoWHellgarve-Legion#405]
The NPC does not loot his item which should drop 100%

https://www.wowhead.com/quest=40039/tharillons-fall#guides
https://www.wowhead.com/npc=98214/herbalist-tharillon

https://cdn.discordapp.com/attachments/1162966799399256134/1162968064736890990/WoWScrnShot_101523_061306.jpg?ex=653ddd69&is=652b6869&hm=0bf664b46c15a053455ccc71654a6593ac00c3b538e79a43d7fc4553fcc49e3e&

**Comment by skeezerbean** [comment]
Sent in a fix for this
