### ISSUE TITLE
Exit Dungeon Que

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#41]
Same issue on Legion Realm https://github.com/holydeew/WoWHellgarve-9.2.x/issues/715

On the Legion realm it sometimes works to quit the dungeon, but sometimes it just bugs out and forces you to relog.

**Comment by skeezerbean** [comment]
Leave the queue when entering the dungeon (not the premade group), should let you exit then instead of waiting
