### ISSUE TITLE
[Quest] [NPC] Death Comes from on High 

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#410]
QUEST ID: [12641](https://www.wowhead.com/quest=12641/death-comes-from-on-high)
NPC ID : [30628](https://www.wowhead.com/npc=30628/eye-of-acherus-dk) or [28511](https://www.wowhead.com/npc=28511/eye-of-acherus)

Issue: I can't move the eye of archerus down or up, only straight forward or back,  that makes it impossible to complete the quest.

Video: [Youtube](https://www.youtube.com/watch?v=9V8KWMMa0aU)

**Comment by skeezerbean** [comment]
Hit space bar to jump, it acts weird but after that it lets you move around as needed
