### ISSUE TITLE
[Quest] [Order Hall] [Death Knight] Maw of Souls: Maul of the Dead 43574

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#411]
Quest ID: [43574](https://www.wowhead.com/quest=43574/maw-of-souls-maul-of-the-dead)
Item ID: [140162](https://www.wowhead.com/item=140162/maul-of-the-dead#contained-in-object)

**Problem explained:** 
Completing Maw of Souls in different difficulties does not drop you the Item after killing Helya. Normally if you got the Quest [Maw of Souls: Maul of the Dead](https://www.wowhead.com/quest=43574/maw-of-souls-maul-of-the-dead) you should be able to loot [Maul of the Dead](https://www.wowhead.com/item=140162/maul-of-the-dead) after killing Helya.

**Comment by skeezerbean** [comment]
It dropped, but was set to like 3%. Adjusted to 100% for quest
