### ISSUE TITLE
[Quest] Away From Prying Eyes [Artifact]

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#42]
**[Quest] Away From Prying Eyes** 
 _https://www.wowhead.com/quest=44782/away-from-prying-eyes_

 **Starts at [NPC] Khadgar** 
 _https://www.wowhead.com/npc=90417/archmage-khadgar_

 **Ends at [NPC] Modera**
 _https://www.wowhead.com/npc=115465/archmage-modera_
 
 
 **Report: Currently the NPCs do not move up the Stairway and also no Portal opens up.**
 
 **How it should work:**
 https://www.youtube.com/watch?v=939xWeySib8

**Comment by skeezerbean** [comment]
Quest will auto complete for now from a nearby NPC until I can get sniff data and script the scene
