### ISSUE TITLE
[Quest] In Dire Need [Artifact]

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#43]
**[Quest] In Dire Need** 
 _https://www.wowhead.com/quest=44821/in-dire-need_

 **Starts at [NPC] Khadgar** 
 _https://www.wowhead.com/npc=115465/archmage-modera_

 **Ends at [NPC] Modera**
 _https://www.wowhead.com/npc=115465/archmage-modera_
 
 
 **Report: You currently can't start the Event**
 
 **How it should work:**
 https://www.youtube.com/watch?v=OOzlXE9oJgA&feature=emb_title

**Comment by skeezerbean** [comment]
Sent in a generic bypass to enable portal and teleport. The rest will get scripted once I can get sniff data
