### ISSUE TITLE
[QUEST][Fragments of Memory] quest item don't stack

### ISSUE THREAD

**Issue by fourbe** [holydeew/WoWHellgarve-Legion#432]
https://www.wowhead.com/quest=40308/fragments-of-memory

in [Fragments of Memory]
item : [Tel'anor Memento]
Don't stack and stay in 15 item

Quest retried, same thing

![Capture d’écran 2024-08-30 165658](https://github.com/user-attachments/assets/8175da6d-7f82-42f3-a4d9-7515bf805b02)
![Capture d’écran 2024-08-30 165929](https://github.com/user-attachments/assets/72389db6-0d3c-4714-bb9e-320839ad31c9)
![Capture d’écran 2024-08-30 170907](https://github.com/user-attachments/assets/9df88465-b04a-462e-a3b0-cb4818ce42ef)

**Comment by skeezerbean** [comment]
I'll be sending in a fix for this soon
