### ISSUE TITLE
[quest=12641][DeathKnight Zone] Death comes form on high

### ISSUE THREAD

**Issue by Selrian** [holydeew/WoWHellgarve-Legion#439]
During the Quest in the Death Knight Starting Zone the Eye of Acherus can't analyze the target New Avalon Forge. This makes the quest not compleatable and makes me stuck in the zone. 
All other target's can be analyzed only this one is not possible for me, tried it on many positions around the forge.

[Quest NPC] New Avalon Forge
[Object] Eye of Acherus Control Mechanism
[Spell] Siphon of Acherus

Source: https://www.wowhead.com/quest=12641/death-comes-from-on-high
https://www.wowhead.com/npc=28525/new-avalon-forge-analyzed
https://www.wowhead.com/spell=51859/siphon-of-acherus

**Comment by skeezerbean** [comment]
Works fine. This is from Hellgarve, right now.

![image](https://github.com/user-attachments/assets/a9546f37-97cb-4fd0-b842-f0793c0b045b)
