### ISSUE TITLE
[General] Quest Icons/Markers/Areas are not Shown

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#44]
In almost 80% of the Legion Quests we are missing Quest Markers/Areas & Icons which makes it hard.

For example this one:
![image](https://user-images.githubusercontent.com/26337071/181150425-6ef33aeb-bf34-4908-88da-a1ccdd2607a9.png)

The Invasion point is no where to be found.

**Comment by skeezerbean** [comment]
I'm not sure invasion points work, but that's a separate issue. POI updates are being sent in for most of Argus. Some are applied already, others still in process of being added.
And no, not 80% of the Legion quests. Most of them are fine across Legion, but Argus specifically had zero.
