### ISSUE TITLE
black rook hold

### ISSUE THREAD

**Issue by FlamingPhoenixOfficial** [holydeew/WoWHellgarve-Legion#443]
Some reason after the maintenance that took place on 18/10/2024 has now caused me to not be able to do black rook hold specially for my mythic+ key that has that dungeon set for. every time i enter it i get 
![image](https://github.com/user-attachments/assets/09691d1a-d904-41a5-a1e7-98bd2d29391d)
 
 
 But before the maintenance that took place i was able to enter it without any issues and without it bugging out my character.
 
 Nothing has changed on my motherboard or bios so its non of that.

**Comment by skeezerbean** [comment]
Fixed
