### ISSUE TITLE
[Quest][Demon Hunter] The Call of War

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#448]
Quest ID: 39691
Quest Link: [The Call of War](https://www.wowhead.com/quest=39691/the-call-of-war)

This Quest is only for Demon Hunters ( Alliance ) 

Bug: So basically there is no Khadgar in Stormwind Keep so thats why this Quest is missing. This Quest is needed to get to Dalaran Legion. 

Edit: I've used the free level 110 Scroll after getting out of Starting Area. Maybe thats why it bugged out.

**Comment by skeezerbean** [comment]
Is Khadgar at the Stormwind entrance? This is where DH teleport to when completing the starter zone, and where Khadgar is at in retail

**Comment by justSelim** [comment]
> Is Khadgar at the Stormwind entrance? This is where DH teleport to when completing the starter zone, and where Khadgar is at in retail

Like I got teleported outside of SW after doing the Starting Area. But he wasnt there neither. And on Wowhead it told me he was at Stormwind Keep, so I looked there too but he wasnt there neither. Maybe it bugged out when I used the lvl 110 scroll

**Comment by skeezerbean** [comment]
I just created a DH, used the boost, and here is Khadgar at the Stormwind entrance

![image](https://github.com/user-attachments/assets/ead8b636-0b34-4162-adef-04fd86780a0a)

**Comment by justSelim** [comment]
Okey thats crazy, I didnt had him. I dont know why. I tried everything like delete cache etc. but a gm helped me out getting that quest. So I dont know why it disappeared for me. Nvm if it works for you it should work for everyone else too. So this is working and can be closed :))
