### ISSUE TITLE
Invasion Points  ( Argus )

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#45]
Currently you can take any quests regarding Invasion Points however you can not complete those.

You don't gain credit after completing the Invasions.

For example: https://www.wowhead.com/quest=48461/where-they-least-expect-it & https://www.wowhead.com/quest=48513/invasion-point-offensive

**Comment by skeezerbean** [comment]
I got credit from multiple invasion points for both of these quests. They work fine to credit these quests.
