### ISSUE TITLE
Wakening Essences Drops / Sources

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#46]
Currently the only way to get Wakening Essences is to do Antorus the Burning Throne however you were also able to get it form this sources:

- First heroic dungeon of the day (30) ( Does not Reset )
- Emissary caches(24-42) ( Haven't gotten any )
- Bosses in [Antorus, the Burning Throne](https://wowpedia.fandom.com/wiki/Antorus,_the_Burning_Throne) on all difficulty levels (18-36) ( Works )
- Weekly Mythic+ chest (120) ( Weren't able to test yet )
- First random battleground win (30), with bonuses during PvP brawl weeks ( Weren't able to test yet )

And in 7.3.5 it got increased by x6
https://wowpedia.fandom.com/wiki/Patch_7.3.5

**Comment by skeezerbean** [comment]
Emissary cache looks like 100% 24-60 of them. If a cache isn't working then I need the exact item ID to check into further. If the others are also not working (not sure what you mean by Does not Reset for heroic) then reopen please.
