### ISSUE TITLE
[Dungeon] Arcway Exit Portal 

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#47]
In the Arcway Dungeon the exit portal does not work.
Whenever you try to go through the portal it won't teleport you out of the Dungeon

**Comment by skeezerbean** [comment]
This works in mythic, but not heroic. Working with a dev to see if the issue can be tracked down. The object for the portal visual had been added, but the actual teleport does not

**Comment by skeezerbean** [comment]
Sent in a fix for this
