### ISSUE TITLE
[Dungeon] [Quest] Eye of Azshara: The Heart of Zin-Azshari

### ISSUE THREAD

**Issue by AvoelDev** [holydeew/WoWHellgarve-Legion#48]
`[Quest]` [Eye of Azshara: The Heart of Zin-Azshari](https://www.wowhead.com/quest=40668/eye-of-azshara-the-heart-of-zin-azshari)
Looted from a Game Object
![image](https://user-images.githubusercontent.com/26337071/182016640-fc594ac4-8a87-4215-8c66-3e894304d89e.png)

`[Item]` [Heart of Zin Azshari](https://www.wowhead.com/item=132738/heart-of-zin-azshari)
`[Object]`[Heart of Zin Azshari](https://www.wowhead.com/object=245934/heart-of-zin-azshari)

You can not loot the Item from the Gameobject.
Tested on all Difficulties ( Mythic is required to complete the quest )

**Comment by AvoelDev** [comment]
![image](https://user-images.githubusercontent.com/26337071/182016769-b2b901e4-45a4-4992-b931-41db93d96ea8.png)
![image](https://user-images.githubusercontent.com/26337071/182016794-f8fc675b-59db-49e5-b408-f646d7ca6bb8.png)

**Comment by AvoelDev** [comment]
Possible fix:

```
DELETE FROM `item_loot_template` WHERE `entry`='245934';
REPLACE INTO `item_loot_template` (`Entry`, `Item`, `ChanceOrQuestChance`, `LootMode`, `Groupid`, `MinCountOrRef`, `MaxCount`) VALUES
(245934, 132738, 100, 1, 0, 1, 1);
```

**Comment by skeezerbean** [comment]
bugged object, sent work-around to Holy
