### ISSUE TITLE
[drak'tharon keep] Mob bug

### ISSUE THREAD

**Issue by MrGrizzlyyyy** [holydeew/WoWHellgarve-Legion#49]
Theres a mob that attacks you while swimming but you cant target or attack it. This link is video evidence of it happening https://drive.google.com/file/d/1fH0nzZrx4boGPRMblL5kBI5GgKpNZ3hi/view?usp=sharing

**Comment by skeezerbean** [comment]
Sent a fix to Holy, NPC shouldn't be untargetable. Not sure what you mean by while swimming though.
