### ISSUE TITLE
Item Bug

### ISSUE THREAD

**Issue by hasblike** [holydeew/WoWHellgarve-Legion#50]
https://www.wowhead.com/item=8628/reins-of-the-spotted-nightsaber

the item is for the alliance faction it cannot be used in the game because it says it requires riding tigers.

![image](https://user-images.githubusercontent.com/33577125/182721658-2cd98a8d-ffc2-40a4-880b-0e7c77b70168.png)

**Comment by skeezerbean** [comment]
Where did it come from? This item has been disabled from dropping since TBC, so I'm guessing the AH probably was selling it from it's store of random IDs. I'll see about getting it removed from the game because you're right they don't work

**Comment by skeezerbean** [comment]
I sent a potential fix to Holy to keep them from showing up in the AH. If it came from elsewhere then let me know. I don't show it in the DB on any vendors so I assume this is where it was at.
