### ISSUE TITLE
[Spell=50977][Death Knight]: Death Gate

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#51]
**The Death Gate is bugged. You can use the spell in your DK and it will take you to your class hall. But if you use again the same spell, it will send you to where your hearthstone is, which is bugged.**

**I have the source and the video to show:**

- Youtube: https://youtu.be/kZkgv9m5pTk

- Source: https://www.wowhead.com/spell=50977/death-gate

**Description: Opens a gate which you can use to return to Ebon Hold.Using a Death Gate while in Ebon Hold will return you back to near your departure point.**

**Comment by asd1488** [comment]
Added image description:

![image](https://user-images.githubusercontent.com/75407049/221352549-44fdf5ef-9354-43c2-adcf-f692a6ea157e.png)

**Comment by skeezerbean** [comment]
Will be sending in a fix for this
