### ISSUE TITLE
[Dungeon] Violet Hold (WOTLK)

### ISSUE THREAD

**Issue by lilkil4** [holydeew/WoWHellgarve-Legion#52]
[NPC] Ichoron
[NPC Spell} Protective Bubble

Issue: protective bubble blocks 99% attacks but should burst after 35 attacks. it doesnt burst because it doesnt count any attack
![Screenshot_7](https://user-images.githubusercontent.com/89088941/184081400-63d1819d-1e1c-4127-8a12-f5d6d2735aa9.png)

**Comment by skeezerbean** [comment]
Sending in a fix for this
