### ISSUE TITLE
[Quest] (Demon Hunter Start Zone) Hidden no more

### ISSUE THREAD

**Issue by lilkil4** [holydeew/WoWHellgarve-Legion#53]
[Quest} [https://www.wowhead.com/quest=39495/hidden-no-more#:~:text=Hidden%20No%20More%20is%20part,the%20The%20Burning%20Crusade%20time.]
[Issue] cave wont open again to go back
![Screenshot_10](https://user-images.githubusercontent.com/89088941/184416305-53518ceb-dacd-4427-a6a5-20187da4cd6b.png)

**Comment by skeezerbean** [comment]
This object is phased and only appears before accepting the quest to go into the cave. If you drop the quest it may phase back in and you'd need to use a hearthstone to exit
