### ISSUE TITLE
[Quest] The Last Emperor

### ISSUE THREAD

**Issue by lilkil4** [holydeew/WoWHellgarve-Legion#55]
[Quest issue] you cant talk to emperor Shaohao because the continue button doesnt prompt the quest to be completed

[Quest ID/Link] [https://www.wowhead.com/quest=33335/the-last-emperor](url)

![Screenshot_12](https://user-images.githubusercontent.com/89088941/184515903-9d92de3e-dd1f-4fef-9bf4-e81b4824ae3f.png)

**Comment by skeezerbean** [comment]
Sent in a fix for this to auto complete when you're near him
