### ISSUE TITLE
[NPC=28921]Hadronox

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#58]
Descript: Hadronox is the second boss in Azjol-Nerub. He is a giant spider, native to Northrend, and opposes the Scourge--players initially encounter him fighting off mobs. He is linked to the achievement [ Hadronox Denied](https://www.wowhead.com/achievement=1297/hadronox-denied).
This NPC can be found in [Azjol-Nerub](javascript:) .

Explanation:
Hadronox get killed by Mobs and doesnt count for the player so player cant get the end reward for doing this dungeon

[Taken from the old Legion bugtracker]

**Comment by skeezerbean** [comment]
Possible fix, will be sending in with next batch soon
