### ISSUE TITLE
[Quest=13167]Death to the Traitor King

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#59]
The quest "Death to the Traitor King" in Aziol Nerub doesnt update after killing Anub'arak he doesnt drop the quest item Anub'araks's Broken Husk

Quest Item= 43411

[Taken from Legion bugtracker]

**Comment by skeezerbean** [comment]
This does indeed drop, but was at 32%. Wowhead shows 38% chance. It was also set only to Normal mode, so if you were in the dungeon in Heroic then it wouldn't have dropped. I'll set it to drop for both
