### ISSUE TITLE
[Quest=13151]A Royal Escort

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#61]
![image](https://user-images.githubusercontent.com/75407049/186046177-4dfd0c6b-3fbd-434a-b8bb-7d2dd5a2aa06.png)

i got Spawned in the town and need to run back to the start of the instance i think it should be fixed if you set the spawn point at the beginning

[Taken from the Legion bugtracker website]

**Comment by skeezerbean** [comment]
I have no idea what that means. Need details of what is actually happening, and what should be happening according to anything official with wow.
