### ISSUE TITLE
[Quest=29828]What the Scourge Dred

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#62]
for the Quest "What the Scourge Dred" (ID 29828) the quest item King Dred's Tooth (Item ID 74755) Doesnt drop to finish this quest

Item=74755

[Taken from the Legion Bug tracker website]

**Comment by skeezerbean** [comment]
Sending a fix for this. It was set to 2% drop rate, wowhead lists as 30%. I changed to 50% because I can. :)
