### ISSUE TITLE
[NPC=90284]Iron Reaver + Invisible wall

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#63]
Hellfire citadel, giant robot protecting the big entrance door is invincible.

Mechanics for defeating this boss do not work.

An invicible wall protect the giant robot.

So, the giant bugued robot boss halts any progression in Hellfire citadel

From Heteropatriarca
[Taken from the Legion Bugtracker website]

**Comment by skeezerbean** [comment]
The robot you saw is the door itself with a funky model. I'll worry about that later. The actual Iron Reaver is set invis, so I removed the aura. He can be attacked and raid can continue now. Sent the fix in for the next server reboot
