### ISSUE TITLE
[Raid: Antorus the Burning Throne] Multiple bugs

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#64]
**Coven of Shivarras:**
NPC=122468

When you finally kill the boss, her body will stay in a place that we can't target or click for loot her.
https://www.wowhead.com/npc=122468/noura-mother-of-flames

**Agrammar:** 
NPC=121975

When you wipe, you can't reach again to the boss., because there's a wall and the bridge is desactivated.
He is using two times his power when he is fully charged: the tank must receive one hit alone and one with the raid band. Instead of that, he is receiving both hits in one time. 
https://www.wowhead.com/spell=243431/taeshalachs-reach
https://www.wowhead.com/npc=121975/aggramar

**Eonar:** 
NPC=131561

Loot is not working properly. I mean.. No loot.
https://www.wowhead.com/npc=131561/essence-of-eonar

**Argus:** 
NPC=124828

Loot chest won't give items.
The boss will be activated by proximity. I think this is bug, because he can be activated in other servers only by the aggro skill (I don't know if in retail is like it).
https://www.wowhead.com/npc=124828/argus-the-unmaker
Also, the items Pantheon's Blessing must be drop 100% per week. Personal loot for each character of the same account.
https://www.wowhead.com/item=155831/pantheons-blessing

**F'harg**
NPC=126916
![image](https://user-images.githubusercontent.com/75407049/186050533-951ae4bf-2c91-44bf-9be4-2671d49bf4ec.png)
In the three encounter NM HC & MM, this NPC will die when you start the attack.
![image](https://user-images.githubusercontent.com/75407049/186050802-ff896e18-9818-47f6-8630-46272491c125.png)

**Personal loot is not working in RAIDS:**
All the Legion raids aren't giving personal loot.. If you, the raid leader has personal loot for the raid, all of your raid members will not get items when you kill a boss. 
It only works when you use "Raid group items loot". So all can do a ninja loot like old times.

**Raid Warning ⚠️: /RW is not working.** 
https://wowpedia.fandom.com/wiki/MACRO_rw
![image](https://user-images.githubusercontent.com/75407049/186050053-9138bd28-0449-4810-9e18-16764edb1d5b.png)

Also you **can't trade items with the other faction** while the Cross Faction it's active. Even if you're in the same raid group.

**Comment by skeezerbean** [comment]
Eonar loot should be fixed once fix applied
Argus chest should be fixed
Raid Warning and cross faction trade fixed.

**Comment by skeezerbean** [comment]
The dogs are fixed - only shared health unless mythic, then each have their own. Attacking one doesn't kill the other anymore

**Comment by skeezerbean** [comment]
I killed Coven of Shivarra, and not seeing a problem. She laid on the ground dead.
