### ISSUE TITLE
[Quest=42534]Our Oldest Enemies

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#65]
https://www.wowhead.com/quest=42534/our-oldest-enemies
![image](https://user-images.githubusercontent.com/75407049/186051285-6c72850a-c2c6-49ff-96f2-386f917173af.png)
Item=138142

Ojin'ba do not drops required item. Head.

Quest for DK Class Hall progression.
![image](https://user-images.githubusercontent.com/75407049/186051393-2345dc46-64c9-473d-856e-cb14b0c1de5a.png)

[Taken from Legion Bugtracker website]

**Comment by skeezerbean** [comment]
Sent in a fix for item drop, as well as the phasing issues that these trolls were invisible/phased and were still able attack players in the zone while on other quests
