### ISSUE TITLE
[NPC=108700]The Monkey King

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#66]
When I complete all the missions of that NPC, I can't complete them with him.

https://www.wowhead.com/npc=108700/the-monkey-king

![image](https://user-images.githubusercontent.com/75407049/186051700-cab8d0c0-ef98-4a33-ac90-0a84333732fd.png)

**Comment by skeezerbean** [comment]
Need more details. This NPC offers 3 quests, and when those are done it should open up quests at another version of this NPC elsewhere as far as I can tell.

**Comment by skeezerbean** [comment]
This NPC is part of the Monk class hall. When all 3 quests are complete, the followup can be found where the riddle of the barrel is at to continue.
