### ISSUE TITLE
[Quest=Multiple quests from all Classes]

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#69]
Good afternoon/evening, the npc yiska (https://es.wowhead.com/npc=118214/yiska#english-comments) does not give the mission (https://www.wowhead.com/quest=46353/master-who ) to start the quest chain for the monk class mount (I have such an achievement that is needed to start the quest chain

photos of achievement and npc that does not give the mission:

https://ibb.co/LzWVNvn

https://ibb.co/nsYQVyP

ps: with my alters the chain of missions should also be unlocked when completing it with 1 but the corresponding npcs of each class have not been given to them either (this report is the one with which I completed all the missions until obtaining said achievement)

[Taken from Legion Bugtracker Website]

**Comment by skeezerbean** [comment]
Quest condition was bound to the wrong achievement ID. A fix has been sent in
