### ISSUE TITLE
[Zone=Broken Shore, Mage Tower]

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#70]
The Mage Tower has a bug that when we want to donate materials it does not leave and it does not activate to enter.
https://wowpedia.fandom.com/wiki/Mage_Tower_(Broken_Shore)

NPC= 119305
https://www.wowhead.com/npc=119305/legionfall-construction-table

NPC= 120183
https://www.wowhead.com/npc=120183/commander-chambers

![image](https://user-images.githubusercontent.com/75407049/186054190-8974e7a4-b221-4925-81ea-5de0a59568ac.png)

**Comment by skeezerbean** [comment]
You can enter fine, but you need to complete the quests as prerequisite. There is an NPC up on the tower area, and if she's there then the tower can be entered IF you have the quest. Make sure all quests are done to open up the quest chain for the mage tower, for that specific class/spec.
The "contribute" buttons on this page will likely never work unless MDic can get them working. Closing for now. The tower works.
