### ISSUE TITLE
[BUG]Hunter Pets

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#71]
Hunter has a Problem With Pet When taming Beast. and relogeas the pet is deleted or when you save it the same thing happened

Also when you try to call your pet, it give you a "internal error" message.

**Comment by skeezerbean** [comment]
I've had no issues taming beasts, abandoning them, relogging and summoning them. If you have something specific then you'll need to give more details. Reopen if needed. If there's an error then a pet likely died and needs resurrected
