### ISSUE TITLE
[Quest=42031]Dire Growth

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#72]
https://www.wowhead.com/quest=42031/dire-growth
Druid Class Hall
There is a mission in the progress of the chapters of val'sharah that is not delivered, said mission is called "

contaminated growth", I don't know if it's bugged, since on the wowhead page when looking for the mission it says this "
This quest has been marked obsolete by Blizzard and cannot be obtained or completed."

![image](https://user-images.githubusercontent.com/75407049/186055337-65ff3989-3205-41a8-bf58-4baed9b7e2a6.png)

**Comment by skeezerbean** [comment]
This should have been fixed with druid class hall updates
