### ISSUE TITLE
[Quest=45035]The Call of Battle

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#73]
https://www.wowhead.com/quest=45035/the-call-of-battle

Destroying the defenses does not count them in the mission and cannot be completed.

![image](https://user-images.githubusercontent.com/75407049/186055564-ca0849cb-e959-41d2-840c-15df1d292ee2.png)

**Comment by skeezerbean** [comment]
Fix sent in, closing
