### ISSUE TITLE
[Quest=39191]Legacy of the Icebreaker

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#74]
Well everything was normal, I let him give his speech and everything, the guards attacked me and I killed them all normal, but after nothing he stopped moving and talking, even the npc called "Hruthnir" who accompanies me stood still.

https://www.wowhead.com/quest=39191/legacy-of-the-icebreaker

![image](https://user-images.githubusercontent.com/75407049/186055739-70e26425-bb29-46c5-b202-87174cc721f6.png)

**Comment by skeezerbean** [comment]
scenario completely rewritten with warrior class hall updates, now fixed and should be working great
