### ISSUE TITLE
[Quest=44751]No Soldier Left Behind

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#75]
https://www.wowhead.com/quest=44751/no-soldier-left-behind

the jail cell don't have soilders to save and that's not how the quest counts
this npc Azsrok the torturer is missing

![image](https://user-images.githubusercontent.com/75407049/186055907-b52bc1f3-1841-49dc-b3fb-4d36e7d28efe.png)

**Comment by skeezerbean** [comment]
Sent a fix for this, closing
