### ISSUE TITLE
[NPC=123689]Talestra the Vile

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#77]
This NPC is not in the map.
https://www.wowhead.com/npc=123689/talestra-the-vile
![image](https://user-images.githubusercontent.com/75407049/186056424-f221eef0-cfad-4b4d-b363-6a0ca55faf1b.png)

Author: pglosocio

**Comment by skeezerbean** [comment]
NPC exists, and is part of a rare NPC pool, not always active. Closing.
![image](https://user-images.githubusercontent.com/19826665/194971617-75fcee6c-f1f1-4405-910c-bb7c1716085a.png)
