### ISSUE TITLE
[Quest=47057]Unholy: The Folly of Levia Laurence

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#78]
https://www.wowhead.com/quest=47057/unholy-the-folly-of-levia-laurence
there is no dialogue with Amisi Azuregaze  in the Legerdemain Lounge in new Dalaran

 Author: gogosixkiller

![image](https://user-images.githubusercontent.com/75407049/186056632-20cebc05-75db-47ad-9f6c-98499ac95765.png)
![image](https://user-images.githubusercontent.com/75407049/186056663-33c8ebcf-43d6-4ccb-846a-a0713c61f8c8.png)
![image](https://user-images.githubusercontent.com/75407049/186056692-6fb4e802-97b8-49df-a528-f2d8a8868370.png)
![image](https://user-images.githubusercontent.com/75407049/186056756-308e4740-ec5a-4b9f-a00c-e49ee2bdbe03.png)

**Comment by skeezerbean** [comment]
Sent fix for multiple quests that all use the same NPCs/gossip/objectives/phasing, fixed gossip issues, fixed gossip options, fixed any scripting issues, fixed Inn Keeper text when in LOS without Dalaran Heathstone, fixed conditions for getting new Hearthstone as well. Closing this slut of an issue.
