### ISSUE TITLE
[NPC=2970]Swoop

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#81]
https://wowpedia.fandom.com/wiki/Bloodhoof_Village

Got chased around and damaged by a dead **Swoop** outside of Bloodhoof Village. Couldn't attack it because I had already killed it.
https://www.wowhead.com/npc=2970/swoop
![image](https://user-images.githubusercontent.com/75407049/186057764-9c97f6e0-f28a-4f6a-928c-f3b4346b3b5c.png)
Author: Kardax

**Comment by skeezerbean** [comment]
Fix for this is sent in
