### ISSUE TITLE
[NPC=22917]Illidan Stormrage <The Betrayer>

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#82]
Ran Black Temple and unable to kill Illidan final boss. He flies up in the air then never comes back down. Tried for 10-15 minutes to no avail. 
https://www.wowhead.com/npc=22917/illidan-stormrage

![image](https://user-images.githubusercontent.com/75407049/186058035-823ee708-93ae-4b9c-8737-96515357584d.png)

 Author: Kardax

**Comment by skeezerbean** [comment]
Sending in a fix
