### ISSUE TITLE
[Quest=37957]Runas the Shamed

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#83]
https://www.wowhead.com/quest=37957/runas-the-shamed

The quest has 2 parts:
- Slay Runas the shamed
- Escort Runas to Senegos

First part works, second part does not complete even with Runas standing next to Senegos.
Talking to either doesn't do anything too.

https://www.wowhead.com/quest=37957/runas-the-shamed#:~:text=You%20can%20find%20Runas%20the,back%20to%20Projection%20of%20Senegos.

![image](https://user-images.githubusercontent.com/75407049/186058254-8742838e-fefc-4fcc-b11f-54a8d0f82cfa.png)

Author: Satan

**Comment by skeezerbean** [comment]
Sent in a quick fix to give credit. Missing text interactions will have to be cleaned up later once the zone gets cleaned up as a whole
