### ISSUE TITLE
Vault of the Wardens

### ISSUE THREAD

**Issue by HelooxD** [holydeew/WoWHellgarve-Legion#84]
If you go to the bottom of the dungeon in the dark, you need to catch up the light to be able to kill the adds.
The light works fine but when you die the light does not reset like in retail Legion neither we at the place where you died.

So after you died once with the light there is no possiblity to grab the light again.

**Comment by skeezerbean** [comment]
I'm not sure what you're referring to. If I die while carrying the light, or not, the fight still resets and it will respawn when Cordana is attacked again.
