### ISSUE TITLE
[Quest-42802]Securing mardum

### ISSUE THREAD

**Issue by MrGrizzlyyyy** [holydeew/WoWHellgarve-Legion#85]
In securing mardum for Demon hunters, theres supposed to be a scouting map in the middle of mardum on the upper layer. It is missing.
![image](https://user-images.githubusercontent.com/110331948/186338143-586c5a95-c3e9-4420-9f6c-ff17ada50499.png)

**Comment by skeezerbean** [comment]
There's a large update to demon hunter class hall pending to be applied, and should clean up most of the issues in the class hall, including phasing and quest order depending on whether you chose Kayn or Altruis
