### ISSUE TITLE
[Quest] [Stormwind City] Diggin' For Worms 26420

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#86]
Quest ID is:
https://www.wowhead.com/quest=26420/diggin-for-worms

The Current Behaviour is as following:
When looting object https://www.wowhead.com/object=204281/worm-mound a loot window appears for a second.
But as result https://www.wowhead.com/item=58788/overgrown-earthworm is not placed in inventory.
Object 204281 correctly despawns after getting looted. And respawns after some time. respawn time might be a bit to long.

**Comment by skeezerbean** [comment]
Sent in a fix for this
