### ISSUE TITLE
[Quest] [Northern Stranglethorn] Panther Prowess ID 192 

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#88]
https://www.wowhead.com/quest=192/panther-prowess

[Shadowmaw Panther] (https://www.wowhead.com/npc=684/shadowmaw-panther) 

Looks to be only spawned 1 times at the Area around Bambala and i need to kill 5 of it so i wait like 20 minutes to finish the quest.

Also this whole questarcs got a autocomplete and go to next quest automatic after you finish the current quest. This is intented, But the Panther quest and the Rapor quest dosent go to the next quest.  
https://www.wowhead.com/quest=194/raptor-hunting 

But that function dont work on this arc. Starting withe https://www.wowhead.com/quest=190/panther-hunting

The Questline https://www.wowhead.com/quest=185/tiger-hunting has the same mechanic but here it works after the quest is finished.

**Comment by skeezerbean** [comment]
Sending in a fix for this - fixed quest flags (all 3 quest chains) for auto complete/accept as needed, and auto-popup in the areas.
The panthers are fine, there are 13 shadowmaw panthers around. Your quest POI should have 3 separate areas, they exist in all 3 but are all sneaking
