### ISSUE TITLE
[Quest] [Northern Stranglethorn] The Mosh'Ogg Bounty | quest=26782 | can be done 2 times

### ISSUE THREAD

**Issue by UrzaPlaneswalker** [holydeew/WoWHellgarve-Legion#90]
https://www.wowhead.com/quest=26782/the-moshogg-bounty quest=26782

This Quest can be completed 2 times.

**Comment by skeezerbean** [comment]
There are 2 different quests which appear almost identical for Alliance, and 2 for Horde. I don't see any comments on which should exist, and which ones are outdated or maybe from another source, so leaving this alone for now until someone finds more details. Until then, enjoy the xp :)

**Comment by UrzaPlaneswalker** [comment]
Thing is i am alliance player and it looks like the crossfaction is making some problems.
Maybe it also corrupts events like the airship in icc. I am not sure about that but i got very often the feeling that i can see more things as i should for my faction.. i saw the horde garrison preparation table and i could interact with the banners.

**Comment by skeezerbean** [comment]
airship in ICC has a whole lot of other issues. For this particular quest in this report, there are a total of 4 that are almost identical. 2 of them for alliance, and 2 of them for horde. This is why you see 2, and I have no details on how they get chained together or if one should be nuked over another one. They would be exclusive in some way, that if you take one then you shouldn't even see the other, but until I get more details on that part of it then we'll see

Garrisons no idea there either. It will be a bit but I'll get around to those as well eventually

**Comment by skeezerbean** [comment]
Sending in a fix for this
