### ISSUE TITLE
[Professions: Mining] Smelting Thorium is learned at a too high skill

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#92]
Smelting Thorium should be availeble at Mining 200, but it's only available at 230.
Additionaly, farming nodes don't always give skillpoints, despite being displayed in orange (which indicates a 100% chance in getting a skillpoint).

![WoWScrnShot_091122_223200](https://user-images.githubusercontent.com/112987767/189547874-358381a7-f5c4-441c-876c-7ea1ab251c9c.jpg)

**Comment by skeezerbean** [comment]
Sending in a fix for this, looks to be working now with 200ish mining and being able to learn/smelt thorium

![image](https://user-images.githubusercontent.com/19826665/195159156-ba9c35f1-8375-4e86-8c20-0d31ac42af57.png)
