### ISSUE TITLE
Shattrath Portal Trainer lets me learn Horde Portals as Ally.

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#93]
I'm pretty sure this should not be possible ...
![WoWScrnShot_091222_003554](https://user-images.githubusercontent.com/112987767/189551760-168fb8f1-616b-4cb0-9732-45e2ca75e946.jpg)

**Comment by skeezerbean** [comment]
We'll look more into this. As human mage it showed only alliance portals until some of the higher level ones (tor borad, etc), but light-forged (which you seem to be) showed all. Couldn't cast them if learned, but checking more into how it displays the list for characters

**Comment by Knuddelmon** [comment]
I'm a Gnome, not Lightforged,

**Comment by skeezerbean** [comment]
It was Iorioa's avatar I was looking at. Either way it happens and we'll look more into when able. Thanks for letting me know

**Comment by skeezerbean** [comment]
I'm sending in a fix for those, seems to be working in testing so far with no side effects.
