### ISSUE TITLE
Quest issue / Further advancement

### ISSUE THREAD

**Issue by hynael1** [holydeew/WoWHellgarve-Legion#94]
When Accpeting the Quest from Advisoer sevel the quest has to be given in on the NPC Journeyman, however the NPC is not accpeting the quest

11299 - https://www.wowhead.com/npc=112199/journeyman-goldmine

46781 - 

96746 - https://www.wowhead.com/quest=46786/further-advancement
![11](https://user-images.githubusercontent.com/113262184/189553610-34c55907-2684-4a6f-becd-4719943eb329.jpg)
![12](https://user-images.githubusercontent.com/113262184/189553611-12c70911-35c7-425c-8279-df64d87e6efb.jpg)
![13](https://user-images.githubusercontent.com/113262184/189553612-b5c45268-680f-498e-b9f1-49ec7c7bfdbf.jpg)

**Comment by hynael1** [comment]
Now cannot even see the NPCs

**Comment by skeezerbean** [comment]
What Class Hall is this? It will have to be sorted later once I run through video/sniff data for it. Most of them have some phasing issues and lots of quest chains out of order or weird conditions for them.

**Comment by skeezerbean** [comment]
Appears to be Shaman, but closing due to lack of response. Will look at it when cleaning up Shaman class hall in general and hopefully resolves, or will get more details then if not.
