### ISSUE TITLE
TOY/Heirloom: Heirloom Flight Path Toy

### ISSUE THREAD

**Issue by ManaInfectedRP** [holydeew/WoWHellgarve-Legion#97]
Alliance toys :
Scouting Map: Surviving Kalimdor https://www.wowhead.com/item=150743/scouting-map-surviving-kalimdor
and
Scouting Map: Modern Provisioning of the Eastern Kingdoms : https://www.wowhead.com/item=150746/scouting-map-modern-provisioning-of-the-eastern-kingdoms

Does not grant all flightpaths for alliances is Eastern Kingdoms or Kalimdor.

**Comment by skeezerbean** [comment]
It's not supposed to grant all. Only a few.
I am sending an update though to update any characters who have this already uploaded and don't have any of the associated flight points, since you cannot upload the toy twice.
