### ISSUE TITLE
[Worgen Starting Zone][QUEST=14218]By Blood and Ash NPC problem?

### ISSUE THREAD

**Issue by asd1488** [holydeew/WoWHellgarve-Legion#98]
In the quest By Blood and Ash, the NPC is not attacking the player, you can kill them, but if your bomb kill the NPC and the others get agro from you, they come to you and if you try to kill them with the bombs or your skills, they evade it. 

But the quest is working. That's the only Issue.
Quest: https://www.wowhead.com/quest=14218/by-blood-and-ash

**Comment by skeezerbean** [comment]
Have a fix for this along with some other Gilneas updates that will be sent in soon, closing this. Re-open if any issues after it gets applied
