### ISSUE TITLE
Cobalt nodes missing

### ISSUE THREAD

**Issue by Knuddelmon** [holydeew/WoWHellgarve-Legion#99]
I just flew along the south coast of Northrend from Westguard Keep to Coldarra, and found 1 (one!) node. (In Emerald Dragon Shrine).
There should be some more, at least according to https://www.wowhead.com/wotlk/object=189978/cobalt-deposit

**Comment by domdiego44** [comment]
Yes, i concur. But i could find 3 nodes in one of the dungeons... it was hard, but i mined them in there.

**Comment by skeezerbean** [comment]
Adding over 600 of them across borean, dragoblight, grizzly and howling zones
